### ISSUE TITLE
[SCM-787] HG plugin failed to blame commit

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#1004]
**[Bastien Cecchinato](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zebasto)** opened **[SCM-787](https://issues.apache.org/jira/browse/SCM-787?redirect=false)** and commented

Hi !

I'm testing SonarQube 5.0-RC3 with the latest snapshot version of sonar-scm-mercurial plugin, but I'm facing an issue when running sonar:sonar command.

The stacktrace is the following :

```
[ERROR] Failed to execute goal org.codehaus.mojo:sonar-maven-plugin:2.4:sonar (default-cli) on project bdm-voice: Error inside stdOut stream [command: hg blame -w -v --user --date --changeset src/main/java/com/worldline/bdm/voice/business/api/client/BNPPHeader.java]: Unable to blame file src/main/java/com/worldline/bdm/voice/business/api/client/BNPPHeader.java. Unrecognized blame info at line 1: Bastien Cecchinato (a528122) 82b11c6cf633 Thu Aug 14 15:30:08 2014 +0200: package com.worldline.bdm.voice.business.api.client; -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:sonar-maven-plugin:2.4:sonar (default-cli) on project bdm-voice: Error inside stdOut stream [command: hg blame -w -v --user --date --changeset src/main/java/com/worldline/bdm/voice/business/api/client/BNPPHeader.java]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error inside stdOut stream [command: hg blame -w -v --user --date --changeset src/main/java/com/worldline/bdm/voice/business/api/client/BNPPHeader.java]
        at org.codehaus.mojo.sonar.bootstrap.ExceptionHandling.handle(ExceptionHandling.java:42)
        at org.codehaus.mojo.sonar.bootstrap.RunnerBootstraper.execute(RunnerBootstraper.java:135)
        at org.codehaus.mojo.sonar.SonarMojo.execute(SonarMojo.java:136)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: org.sonar.api.utils.command.CommandException: Error inside stdOut stream [command: hg blame -w -v --user --date --changeset src/main/java/com/worldline/bdm/voice/business/api/client/BNPPHeader.java]
        at org.sonar.api.utils.command.CommandExecutor.verifyGobbler(CommandExecutor.java:123)
        at org.sonar.api.utils.command.CommandExecutor.execute(CommandExecutor.java:96)
        at org.sonar.plugins.scm.mercurial.MercurialBlameCommand.execute(MercurialBlameCommand.java:108)
        at org.sonar.plugins.scm.mercurial.MercurialBlameCommand.blame(MercurialBlameCommand.java:94)
        at org.sonar.plugins.scm.mercurial.MercurialBlameCommand.access$000(MercurialBlameCommand.java:42)
        at org.sonar.plugins.scm.mercurial.MercurialBlameCommand$1.call(MercurialBlameCommand.java:81)
        at org.sonar.plugins.scm.mercurial.MercurialBlameCommand$1.call(MercurialBlameCommand.java:78)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Unable to blame file src/main/java/com/worldline/bdm/voice/business/api/client/BNPPHeader.java. Unrecognized blame info at line 1: Bastien Cecchinato (a528122) 82b11c6cf633 Thu Aug 14 15:30:08 2014 +0200: package com.worldline.bdm.voice.business.api.client;
        at org.sonar.plugins.scm.mercurial.MercurialBlameConsumer.consumeLine(MercurialBlameConsumer.java:64)
        at org.sonar.api.utils.command.CommandExecutor$StreamGobbler.consumeLine(CommandExecutor.java:191)
        at org.sonar.api.utils.command.CommandExecutor$StreamGobbler.run(CommandExecutor.java:177)
```

I tried to run the hg command directly in the folder :

```
C:\Workspace\bdm-voice-ivr-sources\bdm-voice-business\bdm-voice-business-api-client>hg blame -w -v --user --date --changeset src/main/java/com/worldline/bdm/voice/business/api/client/BNPPHeader.java
Bastien Cecchinato (a528122) 82b11c6cf633 Thu Aug 14 15:30:08 2014 +0200: package com.worldline.bdm.voice.business.api.client;
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200: public enum BNPPHeader {
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:     SESSION_ID("sessionId"),
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:     CALLER_ID("callerId"),
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:     USER_ID("userId"),
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:     REQUEST_TYPE("requestType"),
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:     REQUEST_ID("requestId"),
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:     REQUEST_ERROR_ID("requestErrorId"),
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:     CONTEXT_ID_SENT("contextIdSent"),
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:     CONTEXT_ID_RECEIVED("contextIdReceived"),
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:     SERVER_ID("serverId"),
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:     SERVER_NAME("serverName"),
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:     REQUEST_ATTEMPT_NUMBER("requestAttemptNumber");
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:     private String value;
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:
Bastien Cecchinato (a528122) 4a7987ec947d Mon Aug 25 17:02:09 2014 +0200:     private BNPPHeader(String value) {
Bastien Cecchinato (a528122) 4a7987ec947d Mon Aug 25 17:02:09 2014 +0200:         this.value = value;
Bastien Cecchinato (a528122) 4a7987ec947d Mon Aug 25 17:02:09 2014 +0200:     }
Bastien Cecchinato (a528122) 4a7987ec947d Mon Aug 25 17:02:09 2014 +0200:
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:     public String getValue() {
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:         return value;
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:     }
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:     @Override
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:     public String toString() {
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:         return name() + " [" + this.value + "]";
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:     }
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200:
Bastien Cecchinato (a528122) f3043916657a Wed Aug 13 13:08:13 2014 +0200: }
```

Any idea of what does this issue ?

Regards,

---

**Affects:** 1.13.0

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

This issue has been auto closed because it has been inactive for a long period of time. If you think this issue still applies, retest your problem with the most recent version of Maven and the affected component, reopen and post your results.
