### ISSUE TITLE
[SCM-239] svn-commons doesn't support svn 1.4 working copy format

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#1005]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** opened **[SCM-239](https://issues.apache.org/jira/browse/SCM-239?redirect=false)** and commented

testSvnFromPath(org.apache.maven.scm.provider.svn.repository.SvnScmProviderRepositoryTest)  Time elapsed: 0.022 sec  <<< ERROR!
org.apache.maven.scm.repository.ScmRepositoryException: Can't read /Users/brett/scm/mergere/maestro/maven-scm/maven-scm-providers/ma
ven-scm-providers-svn/maven-scm-provider-svn-commons/.svn/entries
at org.codehaus.plexus.util.xml.pull.MXParser.parseProlog(MXParser.java:1516)
at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1392)
at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1090)
at org.apache.maven.scm.provider.svn.util.EntriesReader.read(EntriesReader.java:57)
at org.apache.maven.scm.provider.svn.AbstractSvnScmProvider.makeProviderScmRepository(AbstractSvnScmProvider.java:119)
at org.apache.maven.scm.provider.svn.repository.SvnScmProviderRepositoryTest.testSvnFromPath(SvnScmProviderRepositoryTest.ja
va:134)

---

**Attachments:**
- [entries](https://issues.apache.org/jira/secure/attachment/12718496/entries) (_482 bytes_)

**Comment by jira-importer** [comment]
**[Kenney Westerhof](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kenney)** commented

Fixed in svn revision 453277, deployed snapshots
