### ISSUE TITLE
[SCM-857] AnnotateConsumer fails to parse author name if name contains dot

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#1078]
**[Rahul Maheshwari](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=indusbull)** opened **[SCM-857](https://issues.apache.org/jira/browse/SCM-857?redirect=false)** and commented

AnnotateConsumer fails to parse author name if accurev user name contains dot (".")

Sample annotation output that contains user name with dot

```java
10 john.x.doe 2017/12/13 15:10:34   buildscript {
10 john.x.doe 2017/12/13 15:10:34       repositories {
10 john.x.doe 2017/12/13 15:10:34           mavenCentral()
10 john.x.doe 2017/12/13 15:10:34       }
10 john.x.doe 2017/12/13 15:10:34       dependencies {
10 john.x.doe 2017/12/13 15:10:34          
10 john.x.doe 2017/12/13 15:10:34       }
10 john.x.doe 2017/12/13 15:10:34   }
```

Exception Details:

```java
Caused by: java.lang.RuntimeException: Unable to parse annotation from line:       10 john.x.doe 2017/12/13 15:10:34   buildscript {
	at org.apache.maven.scm.provider.accurev.cli.AnnotateConsumer.consumeLine(AnnotateConsumer.java:69)
	at org.apache.maven.scm.provider.accurev.cli.CommandOutputConsumer.consumeLine(CommandOutputConsumer.java:51)
	at org.codehaus.plexus.util.cli.StreamPumper.consumeLine(StreamPumper.java:190)
	at org.codehaus.plexus.util.cli.StreamPumper.run(StreamPumper.java:135)
```

---

**Affects:** 1.9.5

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Fixed with [7ee2b5a73d09f3822cb6e775bc52f84f80acdb83](https://gitbox.apache.org/repos/asf?p=maven-scm.git;a=commit;h=7ee2b5a73d09f3822cb6e775bc52f84f80acdb83).
