### ISSUE TITLE
[SCM-1024] maven-scm-plugin tests do not properly check for existence of svn command

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#1248]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** opened **[SCM-1024](https://issues.apache.org/jira/browse/SCM-1024?redirect=false)** and commented

Remove `svn` from `PATH` and see:

```
[INFO] --- maven-invoker-plugin:3.6.0:run (integration-test) @ maven-scm-plugin ---
[INFO] Building: scm-741-validate-scm-url-matches-working-copy\pom.xml
[INFO] run pre-build script prepare.groovy
[INFO] run post-build script verify.groovy
[INFO]   org.apache.maven.shared.scriptinterpreter.ScriptEvaluationException: java.io.IOException: Cannot run program "svn": CreateProcess error=2, Das System kann die angegebene Datei nicht finden
[INFO]           scm-741-validate-scm-url-matches-working-copy\pom.xml FAILED (0.909 s)
[ERROR] -------------------------------------------------
[ERROR]

*** begin build.log for: scm-741-validate-scm-url-matches-working-copy\pom.xml ***
Running pre-build script: D:\Entwicklung\Projekte\maven-scm\maven-scm-plugin\target\it\scm-741-validate-scm-url-matches-working-copy\prepare.groovy
prepare.groovy:
svn --version
java.io.IOException: Cannot run program "svn": CreateProcess error=2, Das System kann die angegebene Datei nicht finden
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:593)
        at java.lang.Runtime.exec(Runtime.java:423)
        at java.lang.Runtime.exec(Runtime.java:320)
        at org.codehaus.groovy.runtime.ProcessGroovyMethods.execute(ProcessGroovyMethods.java:541)
        at org.codehaus.groovy.runtime.dgm$1024.doMethodInvoke(Unknown Source)
        at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
        at Script1.run(Script1.groovy:32)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:460)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:495)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:469)
        at org.apache.maven.shared.scriptinterpreter.GroovyScriptInterpreter.evaluateScript(GroovyScriptInterpreter.java:69)
        at org.apache.maven.shared.scriptinterpreter.ScriptRunner.executeRun(ScriptRunner.java:223)
        at org.apache.maven.shared.scriptinterpreter.ScriptRunner.run(ScriptRunner.java:160)
        at org.apache.maven.plugins.invoker.AbstractInvokerMojo.runBuild(AbstractInvokerMojo.java:1820)
        at org.apache.maven.plugins.invoker.AbstractInvokerMojo.runBuild(AbstractInvokerMojo.java:1542)
        at org.apache.maven.plugins.invoker.AbstractInvokerMojo.lambda$runBuilds$4(AbstractInvokerMojo.java:1304)
        at org.apache.maven.plugins.invoker.JobExecutor.lambda$null$1(JobExecutor.java:62)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.io.IOException: CreateProcess error=2, Das System kann die angegebene Datei nicht finden
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:453)
        at java.lang.ProcessImpl.start(ProcessImpl.java:139)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 21 more
Running post-build script: D:\Entwicklung\Projekte\maven-scm\maven-scm-plugin\target\it\scm-741-validate-scm-url-matches-working-copy\verify.groovy
Finished post-build script: D:\Entwicklung\Projekte\maven-scm\maven-scm-plugin\target\it\scm-741-validate-scm-url-matches-working-copy\verify.groovy
*** end build.log for: scm-741-validate-scm-url-matches-working-copy\pom.xml ***

[ERROR] -------------------------------------------------
[ERROR]
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 0, Failed: 1, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  scm-741-validate-scm-url-matches-working-copy\pom.xml
```

---

**Affects:** 2.0.1

**Remote Links:**
- [GitHub Pull Request #205
](https://github.com/apache/maven-scm/pull/205)

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Fixed with [93d0142a5f242e7616259ae21aa5eed4d3cc1263](https://gitbox.apache.org/repos/asf?p=maven-scm.git;a=commit;h=93d0142a5f242e7616259ae21aa5eed4d3cc1263).
