### ISSUE TITLE
[SCM-16] local provider tests fail

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#277]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** opened **[SCM-16](https://issues.apache.org/jira/browse/SCM-16?redirect=false)** and commented

2 errors:
org.apache.maven.scm.repository.ScmRepositoryException: The connection string didn't contain the expected number of tokens. Expected 2 tokens but got 3 tokens.
at org.apache.maven.scm.provider.local.LocalScmProvider.makeProviderScmRepository(LocalScmProvider.java:56)
at org.apache.maven.scm.manager.DefaultScmManager.makeScmRepository(DefaultScmManager.java:121)

...

org.apache.maven.scm.repository.ScmRepositoryException: The module doesn't exist (root: c:\home\Brett\cvs\maven2\maven-scm\maven-scm-providers\maven-scm-provider-local\target\scm-test\working-copy, module: test-repo).
at org.apache.maven.scm.provider.local.LocalScmProvider.makeProviderScmRepository(LocalScmProvider.java:94)

---
No further details from [SCM-16](https://issues.apache.org/jira/browse/SCM-16?redirect=false)

**Comment by jira-importer** [comment]
**[Emmanuel Venisse](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evenisse)** commented

Fixed.
