### ISSUE TITLE
[SCM-193] NullPointer in local provider update when a new file is added

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#371]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** opened **[SCM-193](https://issues.apache.org/jira/browse/SCM-193?redirect=false)** and commented

org.apache.maven.continuum.scm.ContinuumScmException: Error while update sources.
at org.apache.maven.continuum.scm.DefaultContinuumScm.updateProject(DefaultContinuumScm.java:272)
at org.apache.maven.continuum.core.action.UpdateWorkingDirectoryFromScmContinuumAction.execute(UpdateWorkingDirectoryFromScmContinuumAction.java:58)
at org.apache.maven.continuum.buildcontroller.DefaultBuildController.build(DefaultBuildController.java:166)
at org.apache.maven.continuum.buildcontroller.BuildProjectTaskExecutor.executeTask(BuildProjectTaskExecutor.java:47)
at org.codehaus.plexus.taskqueue.execution.ThreadedTaskQueueExecutor$ExecutorRunnable.run(ThreadedTaskQueueExecutor.java:103)
at java.lang.Thread.run(Thread.java:595)
Caused by: org.apache.maven.scm.ScmException: Exception while executing SCM command.
at org.apache.maven.scm.command.AbstractCommand.execute(AbstractCommand.java:59)
at org.apache.maven.scm.provider.local.LocalScmProvider.update(LocalScmProvider.java:191)
at org.apache.maven.scm.provider.AbstractScmProvider.update(AbstractScmProvider.java:386)
at org.apache.maven.scm.provider.AbstractScmProvider.update(AbstractScmProvider.java:363)
at org.apache.maven.continuum.scm.DefaultContinuumScm.updateProject(DefaultContinuumScm.java:242)
... 5 more
Caused by: java.lang.NullPointerException
at java.util.Date.getMillisOf(Date.java:938)
at java.util.Date.after(Date.java:911)
at org.apache.maven.scm.command.update.AbstractUpdateCommand.executeCommand(AbstractUpdateCommand.java:89)
at org.apache.maven.scm.command.AbstractCommand.execute(AbstractCommand.java:55)
... 9 more

---

**Affects:** 1.0-beta-3

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

File is copied anyway although the exception is thrown

**Comment by jira-importer** [comment]
**[Emmanuel Venisse](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evenisse)** commented

Fixed in AbstractUpdateCommand

**Comment by jira-importer** [comment]
**[Marius Barbulescu](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=marius.barbulescu)** commented

I get the same error in 1.0.3 when the project is scheduled to run.
If I trigger a manual build it works fine.
Probably is not enough information to understand the problem. Please tell me what info do you need and how to get it.

Here is the log:

INFO   | jvm 1    | 2007/04/13 10:30:00 | 2007-04-13 10:30:00,020 [defaultScheduler_Worker-11] INFO  SchedulesActivator             - >>>>>>>>>>>>>>>>>>>>> Executing build job (test)...
INFO   | jvm 1    | 2007/04/13 10:30:00 | 2007-04-13 10:30:00,036 [defaultScheduler_Worker-11] INFO  Continuum                      - Enqueuing 'NSD' (Build definition id=1).
INFO   | jvm 1    | 2007/04/13 10:30:00 | 2007-04-13 10:30:00,036 [defaultScheduler_Worker-11] INFO  Continuum                      - Enqueuing 'OSS_FWK' (Build definition id=11).
INFO   | jvm 1    | 2007/04/13 10:30:00 | 2007-04-13 10:30:00,223 [Thread-2] INFO  ContinuumScm                   - Updating project: id: '1', name 'NSD'.
INFO   | jvm 1    | 2007/04/13 10:30:00 | 2007-04-13 10:30:00,411 [Thread-2] INFO  ScmManager                     - Updating 'c:\installed\continuum-1.0.3\bin\win32\..\..\apps\continuum\working-directory\1' from 'Y:\wran_cm_nsd'.
INFO   | jvm 1    | 2007/04/13 10:31:00 | 2007-04-13 10:31:00,411 [Thread-2] INFO  BuildController                - The project was not built because there are no changes.
INFO   | jvm 1    | 2007/04/13 10:31:00 | 2007-04-13 10:31:00,489 [Thread-2] INFO  ContinuumScm                   - Updating project: id: '11', name 'OSS_FWK'.
INFO   | jvm 1    | 2007/04/13 10:31:00 | 2007-04-13 10:31:00,521 [Thread-2] INFO  ScmManager                     - Updating 'c:\installed\continuum-1.0.3\bin\win32\..\..\apps\continuum\working-directory\11' from 'Y:\ossrc_fwk'.
INFO   | jvm 1    | 2007/04/13 10:31:09 | 2007-04-13 10:31:09,786 [Thread-2] ERROR BuildController                - Error while building project.
INFO   | jvm 1    | 2007/04/13 10:31:09 | org.apache.maven.continuum.scm.ContinuumScmException: Error while update sources.
INFO   | jvm 1    | 2007/04/13 10:31:09 | 	at org.apache.maven.continuum.scm.DefaultContinuumScm.updateProject(DefaultContinuumScm.java:272)
INFO   | jvm 1    | 2007/04/13 10:31:09 | 	at org.apache.maven.continuum.core.action.UpdateWorkingDirectoryFromScmContinuumAction.execute(UpdateWorkingDirectoryFromScmContinuumAction.java:58)
INFO   | jvm 1    | 2007/04/13 10:31:09 | 	at org.apache.maven.continuum.buildcontroller.DefaultBuildController.build(DefaultBuildController.java:166)
INFO   | jvm 1    | 2007/04/13 10:31:09 | 	at org.apache.maven.continuum.buildcontroller.BuildProjectTaskExecutor.executeTask(BuildProjectTaskExecutor.java:47)
INFO   | jvm 1    | 2007/04/13 10:31:09 | 	at org.codehaus.plexus.taskqueue.execution.ThreadedTaskQueueExecutor$ExecutorRunnable.run(ThreadedTaskQueueExecutor.java:103)
INFO   | jvm 1    | 2007/04/13 10:31:09 | 	at java.lang.Thread.run(Thread.java:595)
INFO   | jvm 1    | 2007/04/13 10:31:09 | Caused by: org.apache.maven.scm.ScmException: Exception while executing SCM command.
INFO   | jvm 1    | 2007/04/13 10:31:09 | 	at org.apache.maven.scm.command.AbstractCommand.execute(AbstractCommand.java:59)
INFO   | jvm 1    | 2007/04/13 10:31:09 | 	at org.apache.maven.scm.provider.local.LocalScmProvider.update(LocalScmProvider.java:191)
INFO   | jvm 1    | 2007/04/13 10:31:09 | 	at org.apache.maven.scm.provider.AbstractScmProvider.update(AbstractScmProvider.java:386)
INFO   | jvm 1    | 2007/04/13 10:31:09 | 	at org.apache.maven.scm.provider.AbstractScmProvider.update(AbstractScmProvider.java:363)
INFO   | jvm 1    | 2007/04/13 10:31:09 | 	at org.apache.maven.continuum.scm.DefaultContinuumScm.updateProject(DefaultContinuumScm.java:242)
INFO   | jvm 1    | 2007/04/13 10:31:09 | 	... 5 more
INFO   | jvm 1    | 2007/04/13 10:31:09 | Caused by: java.lang.NullPointerException
INFO   | jvm 1    | 2007/04/13 10:31:09 | 	at java.util.Date.getMillisOf(Date.java:938)
INFO   | jvm 1    | 2007/04/13 10:31:09 | 	at java.util.Date.after(Date.java:911)
INFO   | jvm 1    | 2007/04/13 10:31:09 | 	at org.apache.maven.scm.command.update.AbstractUpdateCommand.executeCommand(AbstractUpdateCommand.java:89)
INFO   | jvm 1    | 2007/04/13 10:31:09 | 	at org.apache.maven.scm.command.AbstractCommand.execute(AbstractCommand.java:55)
INFO   | jvm 1    | 2007/04/13 10:31:09 | 	... 9 more

**Comment by jira-importer** [comment]
**[Marius Barbulescu](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=marius.barbulescu)** commented

I saw in AbstractUpdateCommand this code:

ChangeSet change = (ChangeSet) i.next();

    if ( startDate != null && change.getDate() != null )
    {
        if ( startDate.after( change.getDate() ) )

the NPE comes from here:

    static final long getMillisOf(Date date) {
    if (date.cdate == null) {

means that change.getDate() returns null.

I would update the code like this:

ChangeSet change = (ChangeSet) i.next();
Date changeDate = change.getDate();
if ( startDate != null && changeDate != null )
{
if ( startDate.after( changeDate ) )

**Comment by jira-importer** [comment]
**[Marius Barbulescu](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=marius.barbulescu)** commented

Seems that 1.0.3 Continuum contain 1.0 beta 3 SCM, so it is normal to not work.
I downloaded and build 1.1 version and it works there.
