### ISSUE TITLE
[SCM-120] ClearCase Changelog test failure

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#373]
**[Mike Perham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mperham)** opened **[SCM-120](https://issues.apache.org/jira/browse/SCM-120?redirect=false)** and commented

junit.framework.ComparisonFailure: expected:<...10...> but was:<...09...>

    at junit.framework.Assert.assertEquals(Assert.java:81)
    at junit.framework.Assert.assertEquals(Assert.java:87)
    at org.apache.maven.scm.provider.clearcase.command.changelog.ClearCaseChangeLogCommandTest.testCommandLine(ClearCaseChangeLogCommandTest.java:97)
    at org.apache.maven.scm.provider.clearcase.command.changelog.ClearCaseChangeLogCommandTest.testGetCommandLineWithStartDate(ClearCaseChangeLogCommandTest.java:69)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

---

**Affects:** 1.0-beta-3

**Comment by jira-importer** [comment]
**[Mike Perham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mperham)** commented

I believe this issue is due to timezones.  10-Sep-03 GMT is 09-Sep-03 in my timezone (US Central time).  Can you update the test to be a little more forgiving of this?

**Comment by jira-importer** [comment]
**[Mike Perham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mperham)** commented

This fixes the problem:

Index: src/test/java/org/apache/maven/scm/provider/clearcase/command/changelog/ClearCaseChangeLogCommandTest.java

---

--- src/test/java/org/apache/maven/scm/provider/clearcase/command/changelog/ClearCaseChangeLogCommandTest.java      (revision 365748)
+++ src/test/java/org/apache/maven/scm/provider/clearcase/command/changelog/ClearCaseChangeLogCommandTest.java      (working copy)
@@ -62,7 +62,7 @@
{
String tag = null;

- 

      Date startDate = getDate( 2003, 8, 10, GMT_TIME_ZONE );

+ 

         Date startDate = getDate( 2003, 8, 10 );
      
         Date endDate = null;

@@ -75,7 +75,7 @@
{
String tag = "myBranch";

- 

      Date startDate = getDate( 2003, 8, 10, GMT_TIME_ZONE );

+ 

         Date startDate = getDate( 2003, 8, 10 );
      
         Date endDate = null;

**Comment by jira-importer** [comment]
**[Emmanuel Venisse](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evenisse)** commented

mike,
you can apply your patch and close this issue

**Comment by jira-importer** [comment]
**[Mike Perham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mperham)** commented

Patch applied.
