### ISSUE TITLE
[SCM-153] Continuum fails while trying to build from clearcase

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#393]
**[Dave Dandeneau](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=davedandeneau@yahoo.com)** opened **[SCM-153](https://issues.apache.org/jira/browse/SCM-153?redirect=false)** and commented

When trying to perform a build from continuum I receive the following error:

Provider message: The cleartool command failed.
Command output:

---

cleartool: Error: A registry entry already exists for "dandendj-LNGDAYD-4130684-maven-7".

---

This happens on the second time through. On the first time through I receive:

org.apache.maven.continuum.execution.ContinuumBuildExecutorException: Could not find Maven project descriptor.
at org.apache.maven.continuum.execution.maven.m2.MavenTwoBuildExecutor.updateProjectFromCheckOut(MavenTwoBuildExecutor.java:111)
at org.apache.maven.continuum.core.action.UpdateProjectFromWorkingDirectoryContinuumAction.execute(UpdateProjectFromWorkingDirectoryContinuumAction.java:62)
at org.apache.maven.continuum.buildcontroller.DefaultBuildController.build(DefaultBuildController.java:169)
at org.apache.maven.continuum.buildcontroller.BuildProjectTaskExecutor.executeTask(BuildProjectTaskExecutor.java:53)
at org.codehaus.plexus.taskqueue.execution.ThreadedTaskQueueExecutor$ExecutorRunnable.run(ThreadedTaskQueueExecutor.java:103)
at java.lang.Thread.run(Thread.java:595)

---

**Affects:** 1.0-beta-3

4 votes, 2 watchers

**Comment by jira-importer** [comment]
**[Dave Dandeneau](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=davedandeneau@yahoo.com)** commented

I also receive the error:

---

cleartool: Error: A registry entry already exists for "dandendj-LNGDAYD-4130684-XXX".

---

while performing a release:perform.

**Comment by jira-importer** [comment]
**[Kjetil Ødegaard](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kjetilod)** commented

I don't know if this is related, but I also get the "A registry entry already exists" every time I try to build a ClearCase project from Continuum. "scm:update" works fine from the command line.

**Comment by jira-importer** [comment]
**[Kalle Korhonen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kaosko)** commented

This still happens in 1.0.3. My Clearcase master build works, but sub-module builds and builds from different branches fail with the same exception. I'm building on Linux w/ standard Clearcase 6.x.

**Comment by jira-importer** [comment]
**[Kalle Korhonen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kaosko)** commented

Don't know what the root cause of the problem is but, sometimes the actual build directory isn't created while the view storage directory is. To work around the problem, you can remove the created view storage dir with "cleartool rmview" (check the id of the Continuum build to know which one to remove) and then try again. Once Continuum is happy with the directories and doesn't try re-creating snapshot, but uses update only, the problem is gone.

**Comment by jira-importer** [comment]
**[Emmanuel Venisse](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evenisse)** commented

you can look at clearcase scm provider. If you don't provide a solution for your pb in clearcase provider, we'll can't fix it.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014 if you're wondering why this issue was closed out.
