### ISSUE TITLE
[SCM-338] NullPointerException when using -DvssDirectory to set ss.exe path

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#556]
**[Allan Lang](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=allanlang)** opened **[SCM-338](https://issues.apache.org/jira/browse/SCM-338?redirect=false)** and commented

NullPointerException occurs with any SCM operation when there is no ~/.scm/vss-settings.xml file, and when the vssDirectory system property is set:

```
Caused by: java.lang.NullPointerException
        at org.apache.maven.scm.provider.vss.commands.VssCommandLineUtils.getSettings(VssCommandLineUtils.java:137)
        at org.apache.maven.scm.provider.vss.commands.VssCommandLineUtils.getSsDir(VssCommandLineUtils.java:145)
        at org.apache.maven.scm.provider.vss.commands.changelog.VssHistoryCommand.buildCmdLine(VssHistoryCommand.java:91)
        at org.apache.maven.scm.provider.vss.commands.changelog.VssHistoryCommand.executeChangeLogCommand(VssHistoryCommand.java:53)
        at org.apache.maven.scm.command.changelog.AbstractChangeLogCommand.executeCommand(AbstractChangeLogCommand.java:101)
        at org.apache.maven.scm.command.AbstractCommand.execute(AbstractCommand.java:58)
        ... 21 more
```

This error is easily replicated using the attached project vssproviderbug.zip. Unzip the archive and run

```
mvn scm:changelog -DvssDirectory=something -e
```

Assuming the file ~/.scm/vss-settings.xml does not exist, you should see the above error in the stack traces. Note that you don't need VSS installed (or even to be on Windows) in order to replicate the error - Maven doesn't actually get as far as making a call to ss.exe.

---

**Affects:** 1.0

**Attachments:**
- [SCM-338-[02]-maven-scm-provider-vss.patch](https://issues.apache.org/jira/secure/attachment/12718476/SCM-338-%5B02%5D-maven-scm-provider-vss.patch) (_5.87 kB_)
- [SCM-338-maven-scm-provider-vss.patch](https://issues.apache.org/jira/secure/attachment/12718699/SCM-338-maven-scm-provider-vss.patch) (_649 bytes_)
- [vssproviderbug.zip](https://issues.apache.org/jira/secure/attachment/12718599/vssproviderbug.zip) (_3.01 kB_)

**Comment by jira-importer** [comment]
**[Allan Lang](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=allanlang)** commented

Suggested patch for above issue. Simply instantiates Settings in order to avoid NPE.

**Comment by jira-importer** [comment]
**[Allan Lang](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=allanlang)** commented

Updated patch `SCM-338-[02]-maven-scm-provider-vss.patch` includes a new test case for the `VssCommandLineUtils`, which previously didn't have one.

The test needs to manipulate the `~\.scm\vss-settings.xml` file on disk, which may be a bit suspect depending on how the project is build in CI, so please take a look at what's going on in `VssCommandLineUtilsTest`.
