### ISSUE TITLE
[SCM-340] VSS Provider fails during check out when project path contains spaces

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#568]
**[Allan Lang](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=allanlang)** opened **[SCM-340](https://issues.apache.org/jira/browse/SCM-340?redirect=false)** and commented

VSS Provider fails during check out if project path contains a space. For example, using the following SCM URL:

`scm:vss|guest@\\someserver\somefolder|/top path`

This results in the following output:

```
Executing: "c:\program files\microsoft visual studio\vss\win32\ss" Get "$/project root" -Yguest -R -I- -GWR
Working directory: c:\temp\fiddler
Provider message:
The vss command failed.
Command output:
'c:\program' is not recognized as an internal or external command,
operable program or batch file.

java.lang.Exception: Command failed.The vss command failed.
at com.goongo.vssscmtest.MyTest.checkResult(MyTest.java:125)
at com.goongo.vssscmtest.MyTest.checkOut(MyTest.java:75)
at com.goongo.vssscmtest.MyTest.main(MyTest.java:29)
Exception in thread "main" 
```

This appears to be due to a bug in plexus-utils-1.1. If this dependency is updated to v1.4 (or later) this error is fixed.

Therefore, resolution is to update dependency in pom.xml of maven-scm project.

---

**Affects:** 1.0

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

p-u version has been upgraded in 1.1.
