### ISSUE TITLE
[SCM-376] 'Username isn't defined.' when generating SCM report if CVS port number is specified in SCM URL

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#593]
**[Geert Pante](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=greyfairer)** opened **[SCM-376](https://issues.apache.org/jira/browse/SCM-376?redirect=false)** and commented

I have an CVS connection URL defined as follows:
scm:cvs:pserver:continuum@gnllx002.ebit.be:2401:/data01/cvsroot_bkh:VCG_BKH/uBaseBkh

When I try mvn site, the stage 'Generating "Source Repository" report.' fails as shown below.
If I remove the :2401, it works OK.

[INFO] Generating "Source Repository" report.
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Username isn't defined.
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.IllegalArgumentException: Username isn't defined.
at org.apache.maven.scm.provider.cvslib.repository.CvsScmProviderRepository.getCvsRootForCvsPass(CvsScmProviderRepository.java:105)
at org.apache.maven.scm.provider.cvslib.repository.CvsScmProviderRepository.getCvsRoot(CvsScmProviderRepository.java:73)
at org.apache.maven.report.projectinfo.ScmReport$ScmRenderer.developerAccessCVS(ScmReport.java:479)
at org.apache.maven.report.projectinfo.ScmReport$ScmRenderer.renderDeveloperAccessSection(ScmReport.java:323)
at org.apache.maven.report.projectinfo.ScmReport$ScmRenderer.renderBody(ScmReport.java:186)
at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:65)
at org.apache.maven.report.projectinfo.ScmReport.executeReport(ScmReport.java:87)
at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:101)
at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:139)
at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:269)

---

**Affects:** 1.0

**Issue Links:**
- [SCM-350](https://issues.apache.org/jira/browse/SCM-350) CVS URL without username or password exception

3 votes, 4 watchers

**Comment by jira-importer** [comment]
**[Geert Pante](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=greyfairer)** commented

Same exception, different cause, different scenario.

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

If you are using an empty password, please see http://maven.apache.org/scm/cvs.html in the examples section:

```
 
If you use anonymous access, with an empty password,
you need to add a colon (:) between the username and
"@" like it's done in the first example.
```

**Comment by jira-importer** [comment]
**[Geert Pante](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=greyfairer)** commented

The password is not empty, I'm just using native CVS, with the password in ~/.cvspass.
I'm using the third form from http://maven.apache.org/scm/cvs.html
scm:cvs\<delimiter>pserver\<delimiter>[username[<delimiter>password]@]servername[<delimiter>port]\<delimiter>path_to_repository\<delimiter>module_name
With the [<delimiter>password] left out, and [<delimiter>port] filled in.

Maybe it's better to use an empty password for the continuum user, but we're not an open source company (yet) :-)

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Can you please try this URL instead:
scm:cvs|pserver|continuum@gnllx002.ebit.be:2401|/data01/cvsroot_bkh|VCG_BKH/uBaseBkh

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

I added a test case in [r691838](http://svn.apache.org/viewvc?rev=691838&view=rev)
Could you review it?

**Comment by jira-importer** [comment]
**[Matteo TURRA](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mturra)** commented

I get the same 'Username isn't defined' with | as separator or :
Usually I don't specify username for scm connection because it changes depending who did the checkout and run mvn commands.
I used ${user.name} property to get the current username from shell (ie: ${user.name}`@cvs`.mycompany.com)
I don't know why in another project I didn't put this property and it works!

**Comment by jira-importer** [comment]
**[Matteo TURRA](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mturra)** commented

In the pom I write _scm.connection_ as _scm:cvs:pserver:host:path_

I run _mvn scm:update -Dusername=mturra_

In _org.apache.maven.scm.provider.cvslib.cvsjava.util.CvsConnection.compareCvsRoot(String, String)_ the port parameter are "aligned" by _completeCvsRootPort(String)_ method, but in the ~/.cvspass the cvsroot is in the form _scm:cvs:pserver:_**user@**_host:path_, this is reason why the compareCvsRoot fails and I get the following error:

```
[ERROR] Didn't find password for CVSROOT ':pserver:host/cvsroot'.
org.netbeans.lib.cvsclient.connection.AuthenticationException: Wrong Password.
	at org.netbeans.lib.cvsclient.connection.PServerConnection.openConnection(PServerConnection.java:231)
	at org.netbeans.lib.cvsclient.connection.PServerConnection.open(PServerConnection.java:326)
	at org.apache.maven.scm.provider.cvslib.cvsjava.util.CvsConnection.connect(CvsConnection.java:167)
	at org.apache.maven.scm.provider.cvslib.cvsjava.util.CvsConnection.processCommand(CvsConnection.java:499)
	at org.apache.maven.scm.provider.cvslib.cvsjava.command.update.CvsJavaUpdateCommand.executeCvsCommand(CvsJavaUpdateCommand.java:53)
	at org.apache.maven.scm.provider.cvslib.command.update.AbstractCvsUpdateCommand.executeUpdateCommand(AbstractCvsUpdateCommand.java:79)
	at org.apache.maven.scm.command.update.AbstractUpdateCommand.executeCommand(AbstractUpdateCommand.java:62)
	at org.apache.maven.scm.command.AbstractCommand.execute(AbstractCommand.java:59)
```

I opened another issue for this, see SCM-842

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Is this one still valid?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

No feedback received.
