### ISSUE TITLE
[SCM-408] Support the CVSNT "sserver" protocol

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#633]
**[Cory](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cory)** opened **[SCM-408](https://issues.apache.org/jira/browse/SCM-408?redirect=false)** and commented

When setting the scm developerConnection like the following i get an error that the "sserver" protocol is invalid.

```
<scm>
     <connection/>
     <developerConnection>scm:cvs:sserver:cvsserver:/bigrepo:myproject</developerConnection>
     <tag>HEAD</tag>
     <url>http://cvsserver/ViewVC/viewvc.cgi/myproject/</url>
</scm>
```

The "sserver" protocol is a valid when using cvsnt(pserver over ssl).

I have set the "-Dmaven.scm.provider.cvs.implementation=cvs_native" in the mvn.bat and still get the following error.

```
java.lang.IllegalArgumentException: This SCM url 'scm:cvs:sserver:cvsserver:/bigrepo:commons/myproject' is invalid due to the following errors:
 * Unknown transport: sserver
For more information about SCM URL Format, please refer to: http://maven.apache.org/scm/scm-url-format.html
	at org.apache.maven.report.projectinfo.ScmReport$ScmRenderer.getScmRepository(ScmReport.java:720)
	at org.apache.maven.report.projectinfo.ScmReport$ScmRenderer.renderBody(ScmReport.java:223)
	at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:65)
	at org.apache.maven.report.projectinfo.ScmReport.executeReport(ScmReport.java:124)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:90)
	at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:139)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:269)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:101)
	at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:129)
	at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:96)
	at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:499)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:478)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:291)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
```

---

**Affects:** 1.0

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

As specified on this page http://maven.apache.org/scm/cvs.html "sserver" is not among the supported methods.

**Comment by jira-importer** [comment]
**[Cory](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cory)** commented

Yep, i saw that list. But similar to sspi when you are using the "cvs_native" implementation you should have access to sserver.

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

Fixed in [r691433](http://svn.apache.org/viewvc?rev=691433&view=rev)
Please try it since I am not using this protocol.
