### ISSUE TITLE
[SCM-430] Failed the integration with Starteam 2008 R2

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#644]
**[Elena Rueda](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elena.rueda)** opened **[SCM-430](https://issues.apache.org/jira/browse/SCM-430?redirect=false)** and commented

We are having problems with the integration with starteam provider. To introduce the problem we attached the command output error, pom.xml code, release command, the provider solution and the patch generated.

Command output:

[INFO] Working directory: C:\HADA\PruebasJIRAStarteam
[INFO] Command line: stcmd ci -x -nologo -stop -p E001889@tw0857:49201/P-HADA/PruebasJIRAStarteam -fp C:/HADA/PruebasJIRAStarteam -r "[maven-release-plugin] prepare release PruebasJIRAStarteam-1.5" -eol on pom.xml
[DEBUG] Carpeta: PruebasJIRAStarteam  (directorio de trabajo: C:\HADA\PruebasJIRAStarteam)
[WARNING] Unknown checkin ouput: Carpeta: PruebasJIRAStarteam  (directorio de trabajo: C:\HADA\PruebasJIRAStarteam)
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Unable to commit files
Provider message:
The starteam command failed.
Command output:
el estado es Desconocido, no se incorporará: utilice la opción -o (forzar incorporación)

[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.BuildFailureException: Unable to commit files
Provider message:
The starteam command failed.
Command output:
el estado es Desconocido, no se incorporará: utilice la opción -o (forzar incorporación)

    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:579)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:512)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:482)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:227)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:585)
    at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
    at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
    at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

Caused by: org.apache.maven.plugin.MojoFailureException: Unable to commit files
Provider message:
The starteam command failed.
Command output:
el estado es Desconocido, no se incorporará: utilice la opción -o (forzar incorporación)

    at org.apache.maven.plugins.release.PrepareReleaseMojo.execute(PrepareReleaseMojo.java:144)
    at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
    ... 16 more

[INFO] ------------------------------------------------------------------------
[INFO] Total time: 34 seconds
[INFO] Finished at: Fri Nov 28 15:22:41 CET 2008
[INFO] Final Memory: 5M/9M
[INFO] ------------------------------------------------------------------------

Pom.xml Code:
\<scm>
\<connection>		
scm:starteam:xxxxx:xxxxx@tw0857:49201:/P-HADA/PruebasJIRAStarteam
\</connection>
\<developerConnection>		
scm:starteam:xxxxx:xxxxx@tw0857:49201:/P-HADA/PruebasJIRAStarteam
\</developerConnection>

\</scm>

Release command:
mvn release:prepare -Dusername=xxxxx -Dpassword=xxxxx -Dresume=false -X

Provider solution:
In sort to solve this problem we need to add the "-o" option to the scm command. For it we attached to this issue the patch to apply, where you'll just find added this command to  "maven-scm-provider-starteam".

---

**Affects:** 1.1

**Attachments:**
- [maven-scm-1.1patch.txt](https://issues.apache.org/jira/secure/attachment/12718556/maven-scm-1.1patch.txt) (_879 bytes_)

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

as you say it failed with "Starteam 2008 R2" but will this new option works with old version ?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014 if you're wondering why this issue was closed out.
