### ISSUE TITLE
[SCM-441] NPE when using Git SCM 1.2-SNAPSHOT

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#664]
**[Petter Måhlén](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=petterm)** opened **[SCM-441](https://issues.apache.org/jira/browse/SCM-441?redirect=false)** and commented

This is the log message:
&mdash;
[INFO] Storing revision in 'scm.revision' project property.
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at java.util.Hashtable.put(Hashtable.java:394)
at org.apache.maven.scm.plugin.UpdateMojo.execute(UpdateMojo.java:103)
&mdash;

Looking at the code:

    public void execute()
        throws MojoExecutionException
    {
        super.execute();                                                                                                                              
    
        try
        {
            ScmRepository repository = getScmRepository();                                                                                            
    
            UpdateScmResult result = getScmManager().update( repository, getFileSet(),
                                                             getScmVersion( scmVersionType, scmVersion ),
                                                             runChangelog );                                                                          
    
            checkResult( result );                                                                                                                    
    
            if ( result instanceof UpdateScmResultWithRevision )
            {
                String revision = ( (UpdateScmResultWithRevision) result ).getRevision();                                                             
    
                getLog().info( "Storing revision in '" + revisionKey + "' project property." );                                                       
    
                if ( project.getProperties() != null ) // Remove the test when we'll use plugin-test-harness 1.0-alpha-2
    	{
                    project.getProperties().put( revisionKey, revision );                                                                             
                }
    
                getLog().info( "Project at revision " + revision );                                                                                   
            }
        }
        catch ( IOException e )
        {
            throw new MojoExecutionException( "Cannot run update command : ", e );                                                                    
        }
        catch ( ScmException e )
        {
            throw new MojoExecutionException( "Cannot run update command : ", e );                                                                    
        }
    }

The problem must be that the 'revision' String is null. I guess that is a bug in the Git SCM provider, but I would argue it is also a bug in the Update mojo, which should be a little bit more resistant to null results.

---

**Affects:** 1.2

**Attachments:**
- [SCM-441.patch](https://issues.apache.org/jira/secure/attachment/12718708/SCM-441.patch) (_15.88 kB_)

**Comment by jira-importer** [comment]
**[Petter Måhlén](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=petterm)** commented

Interestingly, this happens whenever there is a valid Git URL in the \<scm/> section of the pom.xml file. but not if I include an invalid SVN url. So my workaround for now to get our builds to work is to lie to the SCM plugin and tell it to use a nonexistent SVN repository.

**Comment by jira-importer** [comment]
**[Mark Struberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=struberg)** commented

please check this patch!

the GitUpdateCommand now detects the latest version of the branch given (or master if non given).

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

you mean please check in or check/verify ? :D.

**Comment by jira-importer** [comment]
**[Mark Struberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=struberg)** commented

Same thing like in a good restaurant:
The question is now WHAT, the question is IN WHICH ORDER!

So I prefer you do both ;)

Would be cool if Petter could also check it on his repo - txs!

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

fixed in [rev 755751](http://svn.apache.org/viewvc?rev=755751&view=rev)
Thanks !
