### ISSUE TITLE
[SCM-469] Auto-generated config spec during release:perform contains line element * null

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#683]
**[Torsten Reinhard](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=reinhart)** opened **[SCM-469](https://issues.apache.org/jira/browse/SCM-469?redirect=false)** and commented

When trying to release a module after migrating from maven-release-plugin 2.0-beta-8 to 2.0-beta-9 I got the following error during mvn release:perform:

[INFO] [release:perform]
[INFO] Checking out the project to perform the release ...
[INFO] Executing: c:\LocalViewsRelease>>cmd.exe /X /C "cleartool mkview -snapshot -tag reinhart-d167961-maven-gide-parent-2.3-alpha-2-SNAPSHOT -vws \\d167961\kmdata\reinhart-d167961-maven-gide-parent-2.3-alpha-2-SNAPSHOT.vws C:\LocalViewsRelease\gi
[INFO] Created config spec for view 'reinhart-d167961-maven-gide-parent-2.3-alpha-2-SNAPSHOT':
element * CHECKEDOUT
element * gide-parent-2.3-alpha-1
element * null
load /GDCAMS/GDCAMS/src/gide-parent

[INFO] Executing: c:\LocalViewsRelease\gide-parent-2.3-alpha-2-SNAPSHOT>>cmd.exe /X /C "cleartool setcs -tag reinhart-d167961-maven-gide-parent-2.3-alpha-2-SNAPSHOT C:\DOKUME~1\reinhart\LOKALE~1\Temp\configspec-reinhart-d167961-maven-gide-parent-2.
[INFO] Executing goals 'deploy site-deploy'...
[WARNING] Base directory is a file. Using base directory as POM location.
[WARNING] Maven will be executed in interactive mode, but no input stream has been configured for this MavenInvoker instance.
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error executing Maven.

Working directory "C:\LocalViewsRelease\gide-parent-2.3-alpha-2-SNAPSHOT\GDCAMS\GDCAMS\src\gide-parent" does not exist!
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error executing Maven.
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:583)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:512)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:482)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:227)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error executing Maven.
at org.apache.maven.plugins.release.PerformReleaseMojo.execute(PerformReleaseMojo.java:133)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
... 16 more
Caused by: org.apache.maven.shared.release.ReleaseExecutionException: Error executing Maven.
at org.apache.maven.shared.release.phase.AbstractRunGoalsPhase.execute(AbstractRunGoalsPhase.java:89)
at org.apache.maven.shared.release.phase.RunPerformGoalsPhase.execute(RunPerformGoalsPhase.java:67)
at org.apache.maven.shared.release.DefaultReleaseManager.perform(DefaultReleaseManager.java:336)
at org.apache.maven.shared.release.DefaultReleaseManager.perform(DefaultReleaseManager.java:282)
at org.apache.maven.shared.release.DefaultReleaseManager.perform(DefaultReleaseManager.java:262)
at org.apache.maven.plugins.release.PerformReleaseMojo.execute(PerformReleaseMojo.java:129)
... 18 more
Caused by: org.apache.maven.shared.release.exec.MavenExecutorException: Error executing Maven.
at org.apache.maven.shared.release.exec.InvokerMavenExecutor.executeGoals(InvokerMavenExecutor.java:391)
at org.apache.maven.shared.release.exec.InvokerMavenExecutor.executeGoals(InvokerMavenExecutor.java:413)
at org.apache.maven.shared.release.phase.AbstractRunGoalsPhase.execute(AbstractRunGoalsPhase.java:81)
... 23 more
Caused by: org.codehaus.plexus.util.cli.CommandLineException: Working directory "C:\LocalViewsRelease\gide-parent-2.3-alpha-2-SNAPSHOT\GDCAMS\GDCAMS\src\gide-parent" does not exist!
at org.codehaus.plexus.util.cli.Commandline.execute(Commandline.java:644)
at org.codehaus.plexus.util.cli.CommandLineUtils.executeCommandLine(CommandLineUtils.java:118)
at org.codehaus.plexus.util.cli.CommandLineUtils.executeCommandLine(CommandLineUtils.java:93)
at org.apache.maven.shared.invoker.DefaultInvoker.executeCommandLine(DefaultInvoker.java:135)
at org.apache.maven.shared.invoker.DefaultInvoker.execute(DefaultInvoker.java:102)
at org.apache.maven.shared.release.exec.InvokerMavenExecutor.executeGoals(InvokerMavenExecutor.java:387)
... 25 more

The line element * null is invalid.

Looking at ClearCaseCheckOutCommand.java I found the following code, causing this problem:

    // write config spec to temp file
    String configSpec;
    if ( repo.hasElements() )
    {
        configSpec = createConfigSpec( repo.getLoadDirectory(), version );
    }
    else
    {
        configSpec = createConfigSpec( repo.getLoadDirectory(), repo.getElementName(), version );
    }

My "workaround" now is to switch back to the maven-release-plugin 2.0-beta-8

---

**Affects:** 1.2

**Attachments:**
- [SCM-469-maven-scm.patch](https://issues.apache.org/jira/secure/attachment/12718560/SCM-469-maven-scm.patch) (_774 bytes_)

3 votes, 1 watchers

**Comment by jira-importer** [comment]
**[Jon Wikman](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=blitter)** commented

Changed if(repo.hasElements()) to if(!repo.hasElements())

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

fixed rev 957259. (snapshot deployed)
Thanks
