### ISSUE TITLE
[SCM-497] Please improve documentation on http://maven.apache.org/scm/guide/usage.html

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#708]
**[Albert Kurucz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ali65)** opened **[SCM-497](https://issues.apache.org/jira/browse/SCM-497?redirect=false)** and commented

Trying to  use Maven-SCM in my application I have selected the "With Plexus IOC" method as provided on http://maven.apache.org/scm/guide/usage.html.
I have made this to a small unit test (attached to this issue), which failed as:

```
Testsuite: com.jtstand.TestEmbedder
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:323)
        at org.codehaus.plexus.embed.Embedder.lookup(Embedder.java:78)
        at com.jtstand.TestEmbedder.<init>(TestEmbedder.java:24)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
        at junit.framework.TestSuite.createTest(TestSuite.java:54)
        at junit.framework.TestSuite.addTestMethod(TestSuite.java:280)
        at junit.framework.TestSuite.<init>(TestSuite.java:140)
        at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:481)
        at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1031)
        at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:888)
))
Tests run: 1, Failures: 1, Errors: 0, Time elapsed: 0.032 sec
```

Please improve usage doc on http://maven.apache.org/scm/guide/usage.html.
Please provide me help getting started in this direction.
Thx.

---

**Affects:** 1.2

**Attachments:**
- [TestEmbedder.java](https://issues.apache.org/jira/secure/attachment/12718558/TestEmbedder.java) (_930 bytes_)

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

don't use the maven embeder but only plexus.

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

instead of using directly the embedder, you should extend [PlexusTestCase](http://plexus.codehaus.org/plexus-containers/plexus-container-default/apidocs/org/codehaus/plexus/PlexusTestCase.html)
