### ISSUE TITLE
[SCM-532] Please add support for blame command

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#745]
**[Mandrikov Evgeny Andreevich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=godin)** opened **[SCM-532](https://issues.apache.org/jira/browse/SCM-532?redirect=false)** and commented

I've made an extension for Maven SCM for blame command. This extension currently part of [Sonar SCM Activity Plugin](http://docs.codehaus.org/display/SONAR/SCM+Activity+Plugin) and supports Subversion (pure Java too), Git, CVS, Mercurial and Bazaar. For all of these providers I made unit-tests. It would be nice to include these command into Maven SCM. Source code can be found here: http://svn.codehaus.org/sonar-plugins/trunk/scm-activity/maven-scm-ext/

---

**Attachments:**
- [SCM-532.diff](https://issues.apache.org/jira/secure/attachment/12718660/SCM-532.diff) (_92.73 kB_)

**Issue Links:**
- [SCM-606](https://issues.apache.org/jira/browse/SCM-606) UnsupportedOperationException on blame GIT
 (_**"is duplicated by"**_)
- [SCM-607](https://issues.apache.org/jira/browse/SCM-607) extend scm:blame BlameLines with author AND committer information

- [SCM-568](https://issues.apache.org/jira/browse/SCM-568) Exception No such command 'blame'

7 votes, 5 watchers

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

As it can be a huge patch.
Could please send a CLA to ASF ? ( see http://www.apache.org/licenses/icla.txt )
I don't have issue for the one I have submitted through my patch in Sonar but for the others.

To others as the code is already ASF license granted do we really need a cla ?

**Comment by jira-importer** [comment]
**[Mandrikov Evgeny Andreevich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=godin)** commented

General question - where I should send it?

**Comment by jira-importer** [comment]
**[Mandrikov Evgeny Andreevich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=godin)** commented

Sended.

**Comment by jira-importer** [comment]
**[Mandrikov Evgeny Andreevich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=godin)** commented

Is there progress? Maybe I can help somehow?

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

ATM not enough spare time (ski holidays coming :-) ).
BTW if you provide a patch it will be faster :P.

**Comment by jira-importer** [comment]
**[Mandrikov Evgeny Andreevich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=godin)** commented

Ok, I'll try to prepare patch.

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

note for maven-scm the code must be 1.4 compatible (not as in sonar where the code use generics)

**Comment by jira-importer** [comment]
**[Mandrikov Evgeny Andreevich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=godin)** commented

Yes, I know ;)

**Comment by jira-importer** [comment]
**[Mandrikov Evgeny Andreevich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=godin)** commented

Code in trunk now Java 1.4 compatible. Is it possible to create branch in maven-scm for me? If not, I'll attach huge patch here.

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

provide your patch

**Comment by jira-importer** [comment]
**[Mandrikov Evgeny Andreevich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=godin)** commented

Patch attached.

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

fixed in [rev 922015](http://svn.apache.org/viewvc?rev=922015&view=rev)
Thanks !

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

Reopen as a tck-git failed

```
mvn clean verify -Ptck-git -Dtest=GitExeBlameCommandTckTest -DfailIfNoTests=false -Dsurefire.useFile=false

junit.framework.ComparisonFailure: expected:<[92f139df]> but was:<[^92f139d]>
        at junit.framework.Assert.assertEquals(Assert.java:81)
        at junit.framework.Assert.assertEquals(Assert.java:87)
        at org.apache.maven.scm.provider.git.gitexe.command.blame.GitExeBlameCommandTckTest.verifyResult(GitExeBlameCommandTckTest.java:53)
        at org.apache.maven.scm.tck.command.blame.BlameCommandTckTest.testBlameCommand(BlameCommandTckTest.java:99)
        at org.apache.maven.scm.provider.git.gitexe.command.blame.GitExeBlameCommandTckTest.testBlameCommand(GitExeBlameCommandTckTest.java:44)
```

This issue happen on solaris env (with git version 1.5.6.2)
But not on windauze (with git version 1.6.5.1.1367.gcd48)

**Comment by jira-importer** [comment]
**[Mandrikov Evgeny Andreevich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=godin)** commented

And I can't reproduce this on my Linux box with git 1.6.4.4

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

so upgrading to git version 1.6.2.1 fix the issue.

**Comment by jira-importer** [comment]
**[Mark Struberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=struberg)** commented

Evgeny, we had a discussion over in SCM-606 of scm:blame should report the 'author' or the 'committer'?
I now assume that the committer information is of better quality (at least for sonar), isn't? Need a quick confirm here ;) txs!

**Comment by jira-importer** [comment]
**[Mandrikov Evgeny Andreevich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=godin)** commented

Hi Mark,

Author is responsible for creation of patch, whereas committer responsible for acceptance of patch, so from my point of view they both responsible for quality of commit. Which means that for quality measures in Sonar it would be better to have access to both values.

**Comment by jira-importer** [comment]
**[Mark Struberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=struberg)** commented

That sounds like we need both fields in the BlameLine. Will create a new Jiraffe for this feature.

**Comment by jira-importer** [comment]
**[Mandrikov Evgeny Andreevich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=godin)** commented

Note that this relates not only to balme, but also to changelog, which should include both authors and committers.
