### ISSUE TITLE
[SCM-538] mvn reactor:make-scm-changes fails for git provider with local git index

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#749]
**[Shankar Narayan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=narashankar)** opened **[SCM-538](https://issues.apache.org/jira/browse/SCM-538?redirect=false)** and commented

I have the following scm connection setup

```xml
<scm>
        <connection>scm:git:file:..</connection>
        <developerConnection>scm:git:file:..</developerConnection>
        <url>scm:git:file:..</url>
    </scm>
```

Regular `mvn scm:*` commands work fine.

The maven reactor plugin seems to have a problem when I issue the following command:

`mvn -X reactor:make-scm-changes`

It complains about invalid scm url. The stack trace seems to point to the scm-provider.

```
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Couldn't configure SCM repository: The scm url is invalid.
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:719)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:569)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:539)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:284)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
        at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Couldn't configure SCM repository: The scm url is invalid.
        at org.apache.maven.plugin.reactor.MakeScmChanges.execute(MakeScmChanges.java:88)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
        ... 17 more
Caused by: org.apache.maven.scm.repository.ScmRepositoryException: The scm url is invalid.
        at org.apache.maven.scm.provider.git.AbstractGitScmProvider.makeProviderScmRepository(AbstractGitScmProvider.java:93)
        at org.apache.maven.scm.manager.AbstractScmManager.makeScmRepository(AbstractScmManager.java:192)
        at org.apache.maven.plugin.reactor.MakeScmChanges.execute(MakeScmChanges.java:83)
        ... 19 more
```

---

**Affects:** 1.3

**Comment by jira-importer** [comment]
**[Mark Struberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=struberg)** commented

I tried it with an absolute file path and it worked well. Can you give us an example of the file:// you used? Is there some weird prefix in cygwin?

**Comment by jira-importer** [comment]
**[Mark Struberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=struberg)** commented

we still got no answer whether the url really was "file:.." or if the two dots were just a placeholder for the real URL. Thus I'm closing this now as illegal.
