### ISSUE TITLE
[SCM-551] Blame command : Unparseable date when locale is not US

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#761]
**[Fabien Bousquet](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=fafanoulele)** opened **[SCM-551](https://issues.apache.org/jira/browse/SCM-551?redirect=false)** and commented

I use blame command for CVS provider and there is this exception :

> [ERROR] skip ParseException: Unparseable date: "17-Jul-07" during parsing date 17-Jul-07 with pattern dd-MMM-yy with Locale en
> java.text.ParseException: Unparseable date: "17-Jul-07"
> at java.text.DateFormat.parse(DateFormat.java:335)
> at org.apache.maven.scm.util.AbstractConsumer.parseDate(AbstractConsumer.java:112)
> at org.apache.maven.scm.util.AbstractConsumer.parseDate(AbstractConsumer.java:68)
> at org.apache.maven.scm.provider.cvslib.command.blame.CvsBlameConsumer.consumeLine(CvsBlameConsumer.java:64)
> at org.codehaus.plexus.util.cli.StreamPumper.consumeLine(StreamPumper.java:195)
> at org.codehaus.plexus.util.cli.StreamPumper.run(StreamPumper.java:144)

I propose a patch to fix this problem.

---

**Affects:** 1.4

**Attachments:**
- [blame-parseexception.patch](https://issues.apache.org/jira/secure/attachment/12718711/blame-parseexception.patch) (_1.31 kB_)

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

fixed rev 952799.
Thanks
