### ISSUE TITLE
[SCM-552] No such command 'add' using Clearcase adaptor when performing release:prepare-with-pom

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#764]
**[Jason Lee](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=xlpeabrain)** opened **[SCM-552](https://issues.apache.org/jira/browse/SCM-552?redirect=false)** and commented

When preparing the release using `release:prepare-with-pom`, the process can not be completed as it seems to try to add the generated `release-pom.xml` into clearcase, but received an error 'No such command 'add' '
From the SCM matrix, it appears that this operation is valid. And ideally, I do not want maven to automatically check in the generated files.

Below is the generated trace:

```
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Cannot add release POM to SCM: No such command 'add'.

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Cannot add release POM t
o SCM: No such command 'add'.
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:719)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandalone
Goal(DefaultLifecycleExecutor.java:569)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defau
ltLifecycleExecutor.java:539)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHan
dleFailures(DefaultLifecycleExecutor.java:387)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmen
ts(DefaultLifecycleExecutor.java:284)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi
fecycleExecutor.java:180)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
        at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:6
0)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Cannot add release PO
M to SCM: No such command 'add'.
        at org.apache.maven.plugins.release.PrepareReleaseMojo.prepareRelease(Pr
epareReleaseMojo.java:215)
        at org.apache.maven.plugins.release.PrepareWithPomReleaseMojo.execute(Pr
epareWithPomReleaseMojo.java:48)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPlugi
nManager.java:490)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:694)
        ... 17 more
Caused by: org.apache.maven.shared.release.ReleaseExecutionException: Cannot add
 release POM to SCM: No such command 'add'.
        at org.apache.maven.shared.release.phase.GenerateReleasePomsPhase.addRel
easePomsToScm(GenerateReleasePomsPhase.java:199)
        at org.apache.maven.shared.release.phase.GenerateReleasePomsPhase.genera
teReleasePoms(GenerateReleasePomsPhase.java:132)
        at org.apache.maven.shared.release.phase.GenerateReleasePomsPhase.execut
e(GenerateReleasePomsPhase.java:105)
        at org.apache.maven.shared.release.phase.GenerateReleasePomsPhase.execut
e(GenerateReleasePomsPhase.java:92)
        at org.apache.maven.shared.release.DefaultReleaseManager.prepare(Default
ReleaseManager.java:203)
        at org.apache.maven.shared.release.DefaultReleaseManager.prepare(Default
ReleaseManager.java:140)
        at org.apache.maven.shared.release.DefaultReleaseManager.prepare(Default
ReleaseManager.java:103)
        at org.apache.maven.plugins.release.PrepareReleaseMojo.prepareRelease(Pr
epareReleaseMojo.java:211)
        ... 20 more
Caused by: org.apache.maven.scm.NoSuchCommandScmException: No such command 'add'
.
        at org.apache.maven.scm.provider.AbstractScmProvider.add(AbstractScmProv
ider.java:147)
        at org.apache.maven.scm.provider.AbstractScmProvider.add(AbstractScmProv
ider.java:141)
        at org.apache.maven.scm.provider.AbstractScmProvider.add(AbstractScmProv
ider.java:124)
        at org.apache.maven.shared.release.phase.GenerateReleasePomsPhase.addRel
easePomsToScm(GenerateReleasePomsPhase.java:190)
        ... 27 more
```

Can anyone make sense of it?

---
No further details from [SCM-552](https://issues.apache.org/jira/browse/SCM-552?redirect=false)

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

> And ideally, I do not want maven to automatically check in the generated files
> In that case you should run the release-plugin with the `prepare`-goal.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

This issue has been auto closed because it has been inactive for a long period of time. If you think this issue still applies, retest your problem with the most recent version of Maven and the affected component, reopen and post your results.
