### ISSUE TITLE
[SCM-556] Vague error message from git-scm-plugin prevents release:prepare

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#766]
**[Paul Hammant](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=paul)** opened **[SCM-556](https://issues.apache.org/jira/browse/SCM-556?redirect=false)** and commented

"Unable to commit files" is vague I think.

The only special thing I'm trying to do is commit from a branch that is not master.  Yes, the branch has remote representation (fully pushed) as well as local.

For the record the project is paranamer on codehaus, which was flipped from Subversion to Git. http://xircles.codehaus.org/projects/paranamer/repo/git/repo  .... real_asm branch.

-e -X console output :

[DEBUG] # On branch real_asm
[DEBUG] # Untracked files:
[DEBUG] #   (use "git add \<file>..." to include in what will be committed)
[DEBUG] #
[DEBUG] #	pom.xml.releaseBackup
[DEBUG] #	release.properties
[DEBUG] nothing added to commit but untracked files present (use "git add" to track)
[INFO] nothing added to commit but untracked files present (use "git add" to track)
[INFO] Executing: /bin/sh -c cd /scm/oss/paranamer-git/paranamer && git commit --verbose -F /var/folders/qb/qbAjORvlEIKOmBNFQArSs++++TI/-Tmp-/maven-scm-890989155.commit pom.xml
[INFO] Working directory: /scm/oss/paranamer-git/paranamer
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Unable to commit files
Provider message:
The git-commit command failed.
Command output:

[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.BuildFailureException: Unable to commit files
Provider message:
The git-commit command failed.
Command output:

    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:715)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:569)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:539)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:284)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
    at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
    at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
    at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

Caused by: org.apache.maven.plugin.MojoFailureException: Unable to commit files
Provider message:
The git-commit command failed.
Command output:

    at org.apache.maven.plugins.release.PrepareReleaseMojo.prepareRelease(PrepareReleaseMojo.java:219)
    at org.apache.maven.plugins.release.PrepareReleaseMojo.execute(PrepareReleaseMojo.java:181)
    at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
    ... 17 more

Caused by: org.apache.maven.shared.release.scm.ReleaseScmCommandException: Unable to commit files
Provider message:
The git-commit command failed.
Command output:

    at org.apache.maven.shared.release.phase.ScmCommitPhase.checkin(ScmCommitPhase.java:133)
    at org.apache.maven.shared.release.phase.ScmCommitPhase.execute(ScmCommitPhase.java:109)
    at org.apache.maven.shared.release.DefaultReleaseManager.prepare(DefaultReleaseManager.java:203)
    at org.apache.maven.shared.release.DefaultReleaseManager.prepare(DefaultReleaseManager.java:140)
    at org.apache.maven.shared.release.DefaultReleaseManager.prepare(DefaultReleaseManager.java:103)
    at org.apache.maven.plugins.release.PrepareReleaseMojo.prepareRelease(PrepareReleaseMojo.java:211)
    ... 20 more

[INFO] ------------------------------------------------------------------------
[INFO] Total time: 55 seconds
[INFO] Finished at: Thu Jun 10 05:35:32 CDT 2010
[INFO] Final Memory: 26M/79M

---

**Affects:** 1.3

**Comment by jira-importer** [comment]
**[Roberto Tyley](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=robertotyley)** commented

The same issue is also affecting me when attempting to release a github-hosted project project:

---

[INFO] Executing: /bin/sh -c cd /home/roberto/development/myproject && git commit --verbose -F /tmp/maven-scm-1979100012.commit pom.xml org.foo.myproject/pom.xml org.foo.myproject.ui/pom.xml
[INFO] Working directory: /home/roberto/development/myproject
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Unable to commit files
Provider message:
The git-commit command failed.
Command output:

---

I notice that the commit message file '/tmp/maven-scm-1979100012.commit' doesn't actually exist...

Apache Maven 2.2.1 (rdebian-1)
Java version: 1.6.0_18
Java home: /usr/lib/jvm/java-6-openjdk/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux" version: "2.6.32-24-generic-pae" arch: "i386" Family: "unix"

**Comment by jira-importer** [comment]
**[Anthony Dahanne](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=anthony.dahanne)** commented

`@Roberto` Tyley : I had exactly the same problem as you; and removing the release.properties and putting back my pom version to a SNAPSHOT (it was previously changed by the plugin) version resolved the problem; the process ended successfully.
Hope it helps !

**Comment by jira-importer** [comment]
**[Daniel Serodio](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dserodio)** commented

I don't understand why this was closed as "Not a bug". The error message is completely misleading.
