### ISSUE TITLE
[SCM-557] ERROR:gitosis.serve.main:Arguments to command look dangerous (apparently)

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#770]
**[Paul Hammant](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=paul)** opened **[SCM-557](https://issues.apache.org/jira/browse/SCM-557?redirect=false)** and commented

Trying to run the release plugin for a git project http://xircles.codehaus.org/projects/paranamer/repo/git/repo (branch real_asm).  In the prepare phase it barfs like so :

```
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] BUILD SUCCESSFUL
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Total time: 11 seconds
[INFO] [INFO] Finished at: Thu Jun 10 05:21:23 CDT 2010
[INFO] [INFO] Final Memory: 39M/81M
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] Checking in modified POMs...
[INFO] Executing: /bin/sh -c cd /scm/oss/paranamer-git/paranamer && git add -- pom.xml
[INFO] Working directory: /scm/oss/paranamer-git/paranamer
[INFO] Executing: /bin/sh -c cd /scm/oss/paranamer-git/paranamer && git status
[INFO] Working directory: /scm/oss/paranamer-git/paranamer
[DEBUG] # On branch real_asm
[DEBUG] # Changes to be committed:
[DEBUG] #   (use "git reset HEAD <file>..." to unstage)
[DEBUG] #
[DEBUG] #	modified:   pom.xml
[DEBUG] #
[DEBUG] # Untracked files:
[DEBUG] #   (use "git add <file>..." to include in what will be committed)
[DEBUG] #
[DEBUG] #	pom.xml.releaseBackup
[DEBUG] #	release.properties
[INFO] Executing: /bin/sh -c cd /scm/oss/paranamer-git/paranamer && git commit --verbose -F /var/folders/qb/qbAjORvlEIKOmBNFQArSs++++TI/-Tmp-/maven-scm-964404670.commit pom.xml
[INFO] Working directory: /scm/oss/paranamer-git/paranamer
[INFO] Executing: /bin/sh -c cd /scm/oss/paranamer-git/paranamer && git symbolic-ref HEAD
[INFO] Working directory: /scm/oss/paranamer-git/paranamer
[INFO] Executing: /bin/sh -c cd /scm/oss/paranamer-git/paranamer && git push ssh://git@git.codehaus.org/paranamer.git/ real_asm:real_asm
[INFO] Working directory: /scm/oss/paranamer-git/paranamer
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Unable to commit files
Provider message:
The git-push command failed.
Command output:
######################################################################
Unauthorized access to this system (codehaus01) is forbidden and will
be prosecuted by law. By accessing this system, you agree that your
actions may be monitored if unauthorized usage is suspected.
######################################################################

ERROR:gitosis.serve.main:Arguments to command look dangerous
fatal: The remote end hung up unexpectedly

[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.BuildFailureException: Unable to commit files
Provider message:
The git-push command failed.
Command output:
######################################################################
Unauthorized access to this system (codehaus01) is forbidden and will
be prosecuted by law. By accessing this system, you agree that your
actions may be monitored if unauthorized usage is suspected.
######################################################################

ERROR:gitosis.serve.main:Arguments to command look dangerous
fatal: The remote end hung up unexpectedly

	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:715)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:569)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:539)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:284)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
	at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoFailureException: Unable to commit files
Provider message:
The git-push command failed.
Command output:
######################################################################
Unauthorized access to this system (codehaus01) is forbidden and will
be prosecuted by law. By accessing this system, you agree that your
actions may be monitored if unauthorized usage is suspected.
######################################################################

ERROR:gitosis.serve.main:Arguments to command look dangerous
fatal: The remote end hung up unexpectedly

	at org.apache.maven.plugins.release.PrepareReleaseMojo.prepareRelease(PrepareReleaseMojo.java:219)
	at org.apache.maven.plugins.release.PrepareReleaseMojo.execute(PrepareReleaseMojo.java:181)
	at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
	... 17 more
Caused by: org.apache.maven.shared.release.scm.ReleaseScmCommandException: Unable to commit files
Provider message:
The git-push command failed.
Command output:
######################################################################
Unauthorized access to this system (codehaus01) is forbidden and will
be prosecuted by law. By accessing this system, you agree that your
actions may be monitored if unauthorized usage is suspected.
######################################################################

ERROR:gitosis.serve.main:Arguments to command look dangerous
fatal: The remote end hung up unexpectedly

	at org.apache.maven.shared.release.phase.ScmCommitPhase.checkin(ScmCommitPhase.java:133)
	at org.apache.maven.shared.release.phase.ScmCommitPhase.execute(ScmCommitPhase.java:109)
	at org.apache.maven.shared.release.DefaultReleaseManager.prepare(DefaultReleaseManager.java:203)
	at org.apache.maven.shared.release.DefaultReleaseManager.prepare(DefaultReleaseManager.java:140)
	at org.apache.maven.shared.release.DefaultReleaseManager.prepare(DefaultReleaseManager.java:103)
	at org.apache.maven.plugins.release.PrepareReleaseMojo.prepareRelease(PrepareReleaseMojo.java:211)
	... 20 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23 seconds
```

---

**Affects:** 1.3

**Comment by jira-importer** [comment]
**[Paul Hammant](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=paul)** commented

So after the fail of this, and before I tidy up working copy, I can experiment some....

ph-mbp:paranamer paul$ git push ssh://git@git.codehaus.org/paranamer.git/ real_asm:real_asm
######################################################################
Unauthorized access to this system (codehaus01) is forbidden and will
be prosecuted by law. By accessing this system, you agree that your
actions may be monitored if unauthorized usage is suspected.
######################################################################

ERROR:gitosis.serve.main:Arguments to command look dangerous
fatal: The remote end hung up unexpectedly
ph-mbp:paranamer paul$ git push ssh://git@git.codehaus.org/paranamer.git/
######################################################################
Unauthorized access to this system (codehaus01) is forbidden and will
be prosecuted by law. By accessing this system, you agree that your
actions may be monitored if unauthorized usage is suspected.
######################################################################

ERROR:gitosis.serve.main:Arguments to command look dangerous
fatal: The remote end hung up unexpectedly
ph-mbp:paranamer paul$ git push codehaus  
######################################################################
Unauthorized access to this system (codehaus01) is forbidden and will
be prosecuted by law. By accessing this system, you agree that your
actions may be monitored if unauthorized usage is suspected.
######################################################################

Counting objects: 42, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (22/22), done.
Writing objects: 100% (22/22), 1.99 KiB, done.
Total 22 (delta 10), reused 0 (delta 0)
To ssh://git@git.codehaus.org/paranamer-git.git
e216419..48f1052  master -> master
b222639..24a42e5  real_asm -> real_asm

Me again -
Is there a reason that the git-scm plugin needs to be so anal with respect to commands ?
Surely it could verify which branch it is on:

> ph-mbp:paranamer paul$ git branch -a
> master
> real_am
> * real_asm
>   remotes/codehaus/master
>   remotes/codehaus/real_asm
>   remotes/github/master
>   remotes/github/real_asm

I'm not using 'origin' to denote origin.  'codehaus' is my origin, 'github' is a mirror.

**Comment by jira-importer** [comment]
**[Darryl L. Miles](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dlmiles)** commented

The message you see is coming from the server ?  It is dangerous since you are not being explicit and the systems at one or both ends need to do some guess work.  This guess can be wrong and therefore for a production system it is dangerous.

A Maven module should not be ambiguously pushing...

Related to SCM-705 ?

    What maven is currently doing:
    git push ssh://git@git.codehaus.org/paranamer.git/ real_asm:real_asm
    
    What maven should be doing:
    git push ssh://git@git.codehaus.org/paranamer.git/ real_asm:refs/heads/real_asm

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

This issue has been auto closed because it has been inactive for a long period of time. If you think this issue still applies, retest your problem with the most recent version of Maven and the affected component, reopen and post your results.
