### ISSUE TITLE
[SCM-569] CVS checkout giving error

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#785]
**[Monica Dube](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=monica)** opened **[SCM-569](https://issues.apache.org/jira/browse/SCM-569?redirect=false)** and commented

I am getting following error when do CVS checkout using maven. Please help me

```
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Command failed.The cvs command failed.
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:719)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:55
6)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.jav
a:387)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
        at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Command failed.The cvs command failed.
        at org.apache.maven.scm.plugin.AbstractScmMojo.checkResult(AbstractScmMojo.java:398)
        at org.apache.maven.scm.plugin.CheckoutMojo.checkout(CheckoutMojo.java:128)
        at org.apache.maven.scm.plugin.CheckoutMojo.execute(CheckoutMojo.java:93)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
        ... 17 more
```

---
No further details from [SCM-569](https://issues.apache.org/jira/browse/SCM-569?redirect=false)

**Comment by jira-importer** [comment]
**[Sanlaville Rémy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sanlavre)** commented

Hi Monica,

What do you mean by ??when do CVS checkout using maven???
Do you want to do your CVS checkout with maven?
What is your maven command?

I think your problem is not related to the scmchangelog-maven-plugin

**Comment by jira-importer** [comment]
**[Monica Dube](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=monica)** commented

I am using maven-scm-plugin plugin and using developerconnection. which has following values
\<developerConnection>scm:cvs:pserver:USER:password#`@IDADRESS`:PORT:/home/cvs:${checkout.module}\</developerConnection>

\<plugin>
			\<groupId>org.apache.maven.plugins\</groupId>
			\<artifactId>maven-scm-plugin\</artifactId>
			\<version>1.3\</version>
			\<executions>
				\<execution>
				\<configuration>
					\<connectionType>developerConnection\</connectionType>
					\<scmVersionType>${cvsTrunkVersion}\</scmVersionType>
					\<scmVersion>${cvsBranchTag}\</scmVersion>
					\<checkoutDirectory>${checkout.destination.dir}\</checkoutDirectory>
				\</configuration>
				 \<phase>process-resources\</phase>
				 \<goals>
					  \<goal>checkout\</goal> 
				 \</goals>
				\</execution>
			\</executions>
		\</plugin>

**Comment by jira-importer** [comment]
**[Sanlaville Rémy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sanlavre)** commented

It seems that your problem is related to [maven-scm-plugin plugin](http://maven.apache.org/scm/plugins/index.html) and not to our [scmchangelog-maven-plugin plugin](http://mojo.codehaus.org/scmchangelog-maven-plugin/).

Post your problem to [maven user mailing list](http://maven-users.828.n2.nabble.com/) or create an issue in the [maven-scm-plugin plugin issue tracker](http://jira.codehaus.org/browse/SCM)

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

This issue has been auto closed because it has been inactive for a long period of time. If you think this issue still applies, retest your problem with the most recent version of Maven and the affected component, reopen and post your results.
