### ISSUE TITLE
[SCM-572] CVS checkout using maven-scm-plugin is not working

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#787]
**[Monica Dube](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=monica)** opened **[SCM-572](https://issues.apache.org/jira/browse/SCM-572?redirect=false)** and commented

I am using `maven-scm-plugin` plugin and using `developerconnection`. which has following values

```xml
<developerConnection>scm:cvs:pserver:USER:password#@IDADRESS:PORT:/home/cvs:${checkout.module}</developerConnection>
```

```xml
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-scm-plugin</artifactId>
<version>1.3</version>
<executions>
<execution>
<configuration>
<connectionType>developerConnection</connectionType>
<scmVersionType>${cvsTrunkVersion}</scmVersionType>
<scmVersion>${cvsBranchTag}</scmVersion>
<checkoutDirectory>${checkout.destination.dir}</checkoutDirectory>
</configuration>
<phase>process-resources</phase>
<goals>
<goal>checkout</goal> 
</goals>
</execution>
</executions>
</plugin>
```

---
No further details from [SCM-572](https://issues.apache.org/jira/browse/SCM-572?redirect=false)

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

and if you use

```xml
<version>1.3</version>
```

?
Btw any stack trace will be appreciate

**Comment by jira-importer** [comment]
**[Monica Dube](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=monica)** commented

It is giving wrong password error but I have checked my authentication is correct and it is working proper with other application.

i-emphsys/emphsysWeb/src/emphsysJAR"
[INFO] Working directory: C:\i-emphsys\emphsysJAR\src\main
org.netbeans.lib.cvsclient.connection.AuthenticationException: Wrong Password.
at org.netbeans.lib.cvsclient.connection.PServerConnection.openConnection(PServerConnection.java:231)
at org.netbeans.lib.cvsclient.connection.PServerConnection.open(PServerConnection.java:326)
at org.apache.maven.scm.provider.cvslib.cvsjava.util.CvsConnection.connect(CvsConnection.java:166)
at org.apache.maven.scm.provider.cvslib.cvsjava.util.CvsConnection.processCommand(CvsConnection.java:498)
at org.apache.maven.scm.provider.cvslib.cvsjava.command.checkout.CvsJavaCheckOutCommand.executeCvsCommand(CvsJav
aCheckOutCommand.java:51)
at org.apache.maven.scm.provider.cvslib.command.checkout.AbstractCvsCheckOutCommand.executeCheckOutCommand(Abstr
actCvsCheckOutCommand.java:90)
at org.apache.maven.scm.command.checkout.AbstractCheckOutCommand.executeCommand(AbstractCheckOutCommand.java:81)

    at org.apache.maven.scm.command.AbstractCommand.execute(AbstractCommand.java:59)
    at org.apache.maven.scm.provider.cvslib.AbstractCvsScmProvider.executeCommand(AbstractCvsScmProvider.java:750)
    at org.apache.maven.scm.provider.cvslib.AbstractCvsScmProvider.checkout(AbstractCvsScmProvider.java:290)
    at org.apache.maven.scm.provider.AbstractScmProvider.checkOut(AbstractScmProvider.java:424)
    at org.apache.maven.scm.provider.AbstractScmProvider.checkOut(AbstractScmProvider.java:401)
    at org.apache.maven.scm.manager.AbstractScmManager.checkOut(AbstractScmManager.java:395)
    at org.apache.maven.scm.plugin.CheckoutMojo.checkout(CheckoutMojo.java:125)
    at org.apache.maven.scm.plugin.CheckoutMojo.execute(CheckoutMojo.java:93)
    at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:55

6) 

       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.jav

a:387)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[ERROR] Provider message:
[ERROR] The cvs command failed.
[ERROR] Command output:
[ERROR]
