### ISSUE TITLE
[SCM-579] No such command 'tag'

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#788]
**[Gergely Kiss](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kgeri)** opened **[SCM-579](https://issues.apache.org/jira/browse/SCM-579?redirect=false)** and commented

The mvn release:prepare fails with the following error when trying to release a trunk checkout with bazaar:

[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] An error is occurred in the tag process: No such command 'tag'.

[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: An error is occurred in the tag process: No such command 'tag'.
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:719)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:569)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:284)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: An error is occurred in the tag process: No such command 'tag'.
at org.apache.maven.plugins.release.PrepareReleaseMojo.execute(PrepareReleaseMojo.java:165)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
... 17 more
Caused by: org.apache.maven.shared.release.ReleaseExecutionException: An error is occurred in the tag process: No such command 'tag'.
at org.apache.maven.shared.release.phase.ScmTagPhase.execute(ScmTagPhase.java:94)
at org.apache.maven.shared.release.DefaultReleaseManager.prepare(DefaultReleaseManager.java:196)
at org.apache.maven.shared.release.DefaultReleaseManager.prepare(DefaultReleaseManager.java:133)
at org.apache.maven.shared.release.DefaultReleaseManager.prepare(DefaultReleaseManager.java:96)
at org.apache.maven.plugins.release.PrepareReleaseMojo.execute(PrepareReleaseMojo.java:161)
... 19 more
Caused by: org.apache.maven.scm.NoSuchCommandScmException: No such command 'tag'.
at org.apache.maven.scm.provider.AbstractScmProvider.tag(AbstractScmProvider.java:677)
at org.apache.maven.scm.provider.AbstractScmProvider.tag(AbstractScmProvider.java:671)
at org.apache.maven.shared.release.phase.ScmTagPhase.execute(ScmTagPhase.java:89)
... 23 more

---

**Affects:** 3.0.0

**Comment by jira-importer** [comment]
**[Gergely Kiss](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kgeri)** commented

Maybe this is also important: the bazaar repository is hosted on a 'dumb' server (bzr+ssh), but is available through sftp. The developerConnection property looks like this:

scm:bazaar:sftp://myuser@bazaarhost/srv/bzr/myproject/trunk

**Comment by jira-importer** [comment]
**[Gergely Kiss](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kgeri)** commented

Sorry for the disturbance, I just found the solution by myself. Bazaar tag support is actually implemented _and released_ in 1.4, but the current maven-release-plugin (2.0) still only uses 1.3 for some reason. It is also weird that the 2.1-SNAPSHOT version of maven-release looks for 1.4-SNAPSHOT (which doesn't exist anymore).

So with a slight hack in the pom, tagging works perfectly with Bazaar:

\<build>
\<plugins>
...
\<plugin>
\<groupId>org.apache.maven.plugins\</groupId>
\<artifactId>maven-release-plugin\</artifactId>
\<version>2.0\</version>
\<dependencies>
\<dependency>
\<groupId>org.apache.maven.scm\</groupId>
\<artifactId>maven-scm-api\</artifactId>
\<version>1.4\</version>
\</dependency>
\<dependency>
\<groupId>org.apache.maven.scm\</groupId>
\<artifactId>maven-scm-provider-bazaar\</artifactId>
\<version>1.4\</version>
\</dependency>
\</dependencies>
\</plugin>
...
\</plugins>
\</build>
