### ISSUE TITLE
[SCM-585] "repository cannot be null" on ScmManager.makeProviderScmRepository(String, File)

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#796]
**[Jörg Hohwiller](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=joerg@j-hohwiller.de)** opened **[SCM-585](https://issues.apache.org/jira/browse/SCM-585?redirect=false)** and commented

I want to update a subversion with maven-scm.
Therefore I get the ScmManager via Plexus and then do this:

```
ScmManager.makeProviderScmRepository("svn", new File(path/to/checkout));
```

What I get is:

```
java.lang.NullPointerException: repository cannot be null
	at org.apache.maven.scm.command.AbstractCommand.execute(AbstractCommand.java:49)
	at org.apache.maven.scm.provider.svn.AbstractSvnScmProvider.executeCommand(AbstractSvnScmProvider.java:356)
	at org.apache.maven.scm.provider.svn.AbstractSvnScmProvider.info(AbstractSvnScmProvider.java:377)
	at org.apache.maven.scm.provider.svn.svnexe.SvnExeScmProvider.getRepositoryURL(SvnExeScmProvider.java:150)
	at org.apache.maven.scm.provider.svn.AbstractSvnScmProvider.makeProviderScmRepository(AbstractSvnScmProvider.java:119)
	at org.apache.maven.scm.manager.AbstractScmManager.makeProviderScmRepository(AbstractScmManager.java:267)
```

From what I understand the code tries to execute "svn info" to get the repository URL.
However executing a command always checks that the repository is not `null`.
In this case the svn command should be executed in order to be able to create the repository.
It is not possible to create the repository before, because the URL is not known.

My suggestion is to revisit this block in AbstractCommand:

```
if ( repository == null )
{
    throw new NullPointerException( "repository cannot be null" );
}
```

---

**Affects:** 1.4

**Comment by jira-importer** [comment]
**[Jörg Hohwiller](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=joerg@j-hohwiller.de)** commented

No feedback after 4 years now... Is maven-scm a dead project?
How does maven update an svn repo after it is checked out? Not at all? Is there a pattern and I am just not seeing how to use the API properly?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

This issue has been auto closed because it has been inactive for a long period of time. If you think this issue still applies, retest your problem with the most recent version of Maven and the affected component, reopen and post your results.
