### ISSUE TITLE
[SCM-597] NPE in AccuRev provider changelog

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#803]
**[Grant Gardner](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lwoggardner)** opened **[SCM-597](https://issues.apache.org/jira/browse/SCM-597?redirect=false)** and commented

org.apache.maven.lifecycle.LifecycleExecutionException: Cannot run changelog command :
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:719)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:569)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:284)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Cannot run changelog command :
at org.apache.maven.scm.plugin.ChangeLogMojo.execute(ChangeLogMojo.java:129)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
... 17 more
Caused by: org.apache.maven.scm.ScmException: Exception while executing SCM command.
at org.apache.maven.scm.command.AbstractCommand.execute(AbstractCommand.java:63)
at org.apache.maven.scm.provider.accurev.command.changelog.AccuRevChangeLogCommand.changelog(AccuRevChangeLogCommand.java:419)
at org.apache.maven.scm.provider.accurev.AccuRevScmProvider.changelog(AccuRevScmProvider.java:390)
at org.apache.maven.scm.provider.AbstractScmProvider.changeLog(AbstractScmProvider.java:250)
at org.apache.maven.scm.plugin.ChangeLogMojo.execute(ChangeLogMojo.java:106)
... 19 more
Caused by: java.lang.NullPointerException
at org.apache.maven.scm.provider.accurev.command.changelog.AccuRevChangeLogCommand.getChangeLog(AccuRevChangeLogCommand.java:406)
at org.apache.maven.scm.provider.accurev.command.changelog.AccuRevChangeLogCommand.executeAccurevCommand(AccuRevChangeLogCommand.java:269)
at org.apache.maven.scm.provider.accurev.command.AbstractAccuRevCommand.executeCommand(AbstractAccuRevCommand.java:66)
at org.apache.maven.scm.command.AbstractCommand.execute(AbstractCommand.java:59)
... 23 more

---

**Affects:** 1.4

**Attachments:**
- [SCM-597.patch](https://issues.apache.org/jira/secure/attachment/12718898/SCM-597.patch) (_1.90 kB_)

**Comment by jira-importer** [comment]
**[Grant Gardner](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lwoggardner)** commented

will work on a patch this w/e

**Comment by jira-importer** [comment]
**[Grant Gardner](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lwoggardner)** commented

In some cases we see diff output with a \<Change what="eid"> which indicates an element has been replaced but contains no filename information. This patch ignores those entries as they are not meaningful for the change log.

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

fixed rev 1062063.
Thanks.
