### ISSUE TITLE
[SCM-593] Blame command: Unparseable date when locale is not US

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#809]
**[Lukasz Kozerski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kozerskil)** opened **[SCM-593](https://issues.apache.org/jira/browse/SCM-593?redirect=false)** and commented

Same problem as here: http://jira.codehaus.org/browse/SCM-551. Moreover exception message is not correct: org.apache.maven.scm.util.AbstractConsumer, line 120:

> " with Locale " + ( locale == null ? Locale.ENGLISH : locale )
> while we use
> format = new SimpleDateFormat( defaultPattern );
> with default locale.

Simple fix: on line 97, change

> format = new SimpleDateFormat( defaultPattern );
> to:
> format = new SimpleDateFormat( defaultPattern, Locale.US );

Stack trace:

> EXECUTING: cmd.exe /X /C "hg blame --user --date --number AbstractSiebelOperations.java"
> [ERROR] skip ParseException: Unparseable date: "Thu Jul 08 11:42:09 2010 +0200" during parsing date Thu Jul 08 11:42:09
> 2010 +0200 with pattern EEE MMM dd HH:mm:ss yyyy Z with Locale en
> java.text.ParseException: Unparseable date: "Thu Jul 08 11:42:09 2010 +0200"
> at java.text.DateFormat.parse(DateFormat.java:337)
> at org.apache.maven.scm.util.AbstractConsumer.parseDate(AbstractConsumer.java:112)
> at org.apache.maven.scm.util.AbstractConsumer.parseDate(AbstractConsumer.java:68)

---

**Affects:** 1.4

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014 if you're wondering why this issue was closed out.
