### ISSUE TITLE
[SCM-618] StringIndexOutOfBoundsException when doing checkout from SVN in combination with plexus-utils:2.0.5+

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#827]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** opened **[SCM-618](https://issues.apache.org/jira/browse/SCM-618?redirect=false)** and commented

Running `mvn clean generate-sources` on the attached POM yields

```
+ Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building Unnamed - test:test:jar:0.1
[INFO]    task-segment: [clean, generate-sources]
[INFO] ------------------------------------------------------------------------
[INFO] [clean:clean {execution: default-clean}]
[INFO] Deleting directory D:\z\target
[INFO] [scm:checkout {execution: checkout}]
[INFO] Removing D:\z\target\maven-model
[INFO] Executing: cmd.exe /X /C "svn --non-interactive checkout http://svn.apache.org/repos/asf/maven/pom/trunk/maven "D:\z\target\maven-model""
[INFO] Working directory: D:\z\target
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Cannot run checkout command : 

Embedded error: Exception while executing SCM command.
String index out of range: -1
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Cannot run checkout command : 
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:719)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
	at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:592)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Cannot run checkout command : 
	at org.apache.maven.scm.plugin.CheckoutMojo.checkout(CheckoutMojo.java:137)
	at org.apache.maven.scm.plugin.CheckoutMojo.execute(CheckoutMojo.java:93)
	at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
	... 17 more
Caused by: org.apache.maven.scm.ScmException: Exception while executing SCM command.
	at org.apache.maven.scm.command.AbstractCommand.execute(AbstractCommand.java:63)
	at org.apache.maven.scm.provider.svn.AbstractSvnScmProvider.executeCommand(AbstractSvnScmProvider.java:356)
	at org.apache.maven.scm.provider.svn.AbstractSvnScmProvider.checkout(AbstractSvnScmProvider.java:292)
	at org.apache.maven.scm.provider.AbstractScmProvider.checkOut(AbstractScmProvider.java:428)
	at org.apache.maven.scm.provider.AbstractScmProvider.checkOut(AbstractScmProvider.java:405)
	at org.apache.maven.scm.manager.AbstractScmManager.checkOut(AbstractScmManager.java:399)
	at org.apache.maven.scm.plugin.CheckoutMojo.checkout(CheckoutMojo.java:125)
	... 20 more
Caused by: org.apache.maven.scm.ScmException: Error while executing command.
	at org.apache.maven.scm.provider.svn.svnexe.command.checkout.SvnCheckOutCommand.executeCheckOutCommand(SvnCheckOutCommand.java:95)
	at org.apache.maven.scm.command.checkout.AbstractCheckOutCommand.executeCommand(AbstractCheckOutCommand.java:82)
	at org.apache.maven.scm.command.AbstractCommand.execute(AbstractCommand.java:59)
	... 26 more
Caused by: org.codehaus.plexus.util.cli.CommandLineException: Error inside systemOut parser
	at org.codehaus.plexus.util.cli.CommandLineUtils.executeCommandLine(CommandLineUtils.java:222)
	at org.codehaus.plexus.util.cli.CommandLineUtils.executeCommandLine(CommandLineUtils.java:107)
	at org.apache.maven.scm.provider.svn.svnexe.command.SvnCommandLineUtils.execute(SvnCommandLineUtils.java:142)
	at org.apache.maven.scm.provider.svn.svnexe.command.checkout.SvnCheckOutCommand.executeCheckOutCommand(SvnCheckOutCommand.java:91)
	... 28 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1768)
	at java.lang.String.substring(String.java:1735)
	at org.apache.maven.scm.provider.svn.svnexe.command.checkout.SvnCheckOutConsumer.parseLine(SvnCheckOutConsumer.java:57)
	at org.apache.maven.scm.provider.svn.svnexe.command.AbstractFileCheckingConsumer.consumeLine(AbstractFileCheckingConsumer.java:68)
	at org.codehaus.plexus.util.cli.StreamPumper.consumeLine(StreamPumper.java:197)
	at org.codehaus.plexus.util.cli.StreamPumper.run(StreamPumper.java:137)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3 seconds
[INFO] Finished at: Thu Apr 07 17:20:00 CEST 2011
[INFO] Final Memory: 26M/355M
[INFO] ------------------------------------------------------------------------
```

There is a bug in the SvnCheckOutConsumer which as of plexus-utils:2.0.5 blows up the entire process.

---

**Affects:** 1.5

**Attachments:**
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12718668/pom.xml) (_2.05 kB_)

1 votes, 0 watchers

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Fixed in [rev. 1241192](http://svn.apache.org/viewvc?rev=1241192&view=rev)
