### ISSUE TITLE
[SCM-641] NPE when workingDirectory is null

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#849]
**[Thibault Kruse](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tibo1979)** opened **[SCM-641](https://issues.apache.org/jira/browse/SCM-641?redirect=false)** and commented

$ maven-scm-client checkout rx scm:svn:https://code.ros.org/svn/ros/stacks/rx/tags/rx-1.6.1
[INFO] Executing: /bin/sh -c svn --non-interactive checkout https://code.ros.org/svn/ros/stacks/rx/tags/rx-1.6.1 /home/tk/work/rx
Error while executing the SCM command.
org.apache.maven.scm.ScmException: Exception while executing SCM command.
at org.apache.maven.scm.command.AbstractCommand.execute(AbstractCommand.java:63)
at org.apache.maven.scm.provider.svn.AbstractSvnScmProvider.executeCommand(AbstractSvnScmProvider.java:356)
at org.apache.maven.scm.provider.svn.AbstractSvnScmProvider.checkout(AbstractSvnScmProvider.java:292)
at org.apache.maven.scm.provider.AbstractScmProvider.checkOut(AbstractScmProvider.java:428)
at org.apache.maven.scm.provider.AbstractScmProvider.checkOut(AbstractScmProvider.java:405)
at org.apache.maven.scm.manager.AbstractScmManager.checkOut(AbstractScmManager.java:399)
at org.apache.maven.scm.client.cli.MavenScmCli.checkOut(MavenScmCli.java:238)
at org.apache.maven.scm.client.cli.MavenScmCli.execute(MavenScmCli.java:190)
at org.apache.maven.scm.client.cli.MavenScmCli.main(MavenScmCli.java:154)
Caused by: java.lang.NullPointerException
at org.apache.maven.scm.provider.svn.svnexe.command.checkout.SvnCheckOutCommand.executeCheckOutCommand(SvnCheckOutCommand.java:86)
at org.apache.maven.scm.command.checkout.AbstractCheckOutCommand.executeCommand(AbstractCheckOutCommand.java:82)
at org.apache.maven.scm.command.AbstractCommand.execute(AbstractCommand.java:59)
... 8 more

---

**Affects:** 1.5

**Comment by jira-importer** [comment]
**[Thibault Kruse](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tibo1979)** commented

Same for git and hg:
Error while executing the SCM command.
org.apache.maven.scm.ScmException: Exception while executing SCM command.
at org.apache.maven.scm.command.AbstractCommand.execute(AbstractCommand.java:63)
at org.apache.maven.scm.provider.git.AbstractGitScmProvider.executeCommand(AbstractGitScmProvider.java:290)
at org.apache.maven.scm.provider.git.AbstractGitScmProvider.checkout(AbstractGitScmProvider.java:226)
at org.apache.maven.scm.provider.AbstractScmProvider.checkOut(AbstractScmProvider.java:428)
at org.apache.maven.scm.provider.AbstractScmProvider.checkOut(AbstractScmProvider.java:405)
at org.apache.maven.scm.manager.AbstractScmManager.checkOut(AbstractScmManager.java:399)
at org.apache.maven.scm.client.cli.MavenScmCli.checkOut(MavenScmCli.java:238)
at org.apache.maven.scm.client.cli.MavenScmCli.execute(MavenScmCli.java:190)
at org.apache.maven.scm.client.cli.MavenScmCli.main(MavenScmCli.java:154)
Caused by: java.lang.NullPointerException
at org.apache.maven.scm.provider.git.gitexe.command.GitCommandLineUtils.getBaseGitCommandLine(GitCommandLineUtils.java:89)
at org.apache.maven.scm.provider.git.gitexe.command.checkout.GitCheckOutCommand.createCloneCommand(GitCheckOutCommand.java:152)
at org.apache.maven.scm.provider.git.gitexe.command.checkout.GitCheckOutCommand.executeCheckOutCommand(GitCheckOutCommand.java:83)
at org.apache.maven.scm.command.checkout.AbstractCheckOutCommand.executeCommand(AbstractCheckOutCommand.java:82)
at org.apache.maven.scm.command.AbstractCommand.execute(AbstractCommand.java:59)

Error while executing the SCM command.
org.apache.maven.scm.ScmException: Exception while executing SCM command.
at org.apache.maven.scm.command.AbstractCommand.execute(AbstractCommand.java:63)
at org.apache.maven.scm.provider.hg.HgScmProvider.checkout(HgScmProvider.java:235)
at org.apache.maven.scm.provider.AbstractScmProvider.checkOut(AbstractScmProvider.java:428)
at org.apache.maven.scm.provider.AbstractScmProvider.checkOut(AbstractScmProvider.java:405)
at org.apache.maven.scm.manager.AbstractScmManager.checkOut(AbstractScmManager.java:399)
at org.apache.maven.scm.client.cli.MavenScmCli.checkOut(MavenScmCli.java:238)
at org.apache.maven.scm.client.cli.MavenScmCli.execute(MavenScmCli.java:190)
at org.apache.maven.scm.client.cli.MavenScmCli.main(MavenScmCli.java:154)
Caused by: java.lang.NullPointerException
at org.apache.maven.scm.provider.hg.HgUtils.buildCmd(HgUtils.java:149)
at org.apache.maven.scm.provider.hg.HgUtils.execute(HgUtils.java:89)
at org.apache.maven.scm.provider.hg.command.checkout.HgCheckOutCommand.executeCheckOutCommand(HgCheckOutCommand.java:79)
at org.apache.maven.scm.command.checkout.AbstractCheckOutCommand.executeCommand(AbstractCheckOutCommand.java:82)
at org.apache.maven.scm.command.AbstractCommand.execute(AbstractCommand.java:59)

So I'll guess the bug is in an abstract class

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Seems like the `workingDir` can be `null`. This has already been fixed for Git, the others still call `workingDir.getAbsolutePath()` which causes the NPE.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Actually, (and here's the real question from Olivier) what did you do to get this exception? What caused the workingDirectory to be `null`? Did you use the maven-release-plugin or maven-scm-plugin or ...?

**Comment by jira-importer** [comment]
**[Thibault Kruse](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tibo1979)** commented

I do:

$ svn checkout http://svn.apache.org/repos/asf/maven/scm/tags/maven-scm-1.6/maven-scm-client maven-scm-client
$ cd maven-scm-client
$ mvn install
$ cd ..
$ cp ..../maven-scm-client-1.6-jar-with-dependencies.jar .
$ java -jar maven-scm-client-1.6-jar-with-dependencies.jar
Usage: maven-scm-client \<command> \<working directory> \<scm url> [\<scmVersion> [<scmVersionType>]]
$ java -jar maven-scm-client-1.6-jar-with-dependencies.jar checkout rx scm:svn:https://code.ros.org/svn/ros/stacks/rx/tags/rx-1.6.1
[INFO] Executing: /bin/sh -c svn --non-interactive checkout https://code.ros.org/svn/ros/stacks/rx/tags/rx-1.6.1 /home/kruset/work/java/rx
Error while executing the SCM command.
org.apache.maven.scm.ScmException: Exception while executing SCM command.
at org.apache.maven.scm.command.AbstractCommand.execute(AbstractCommand.java:63)
at org.apache.maven.scm.provider.svn.AbstractSvnScmProvider.executeCommand(AbstractSvnScmProvider.java:356)
at org.apache.maven.scm.provider.svn.AbstractSvnScmProvider.checkout(AbstractSvnScmProvider.java:292)
at org.apache.maven.scm.provider.AbstractScmProvider.checkOut(AbstractScmProvider.java:480)
at org.apache.maven.scm.provider.AbstractScmProvider.checkOut(AbstractScmProvider.java:453)
at org.apache.maven.scm.manager.AbstractScmManager.checkOut(AbstractScmManager.java:399)
at org.apache.maven.scm.client.cli.MavenScmCli.checkOut(MavenScmCli.java:238)
at org.apache.maven.scm.client.cli.MavenScmCli.execute(MavenScmCli.java:190)
at org.apache.maven.scm.client.cli.MavenScmCli.main(MavenScmCli.java:154)
Caused by: java.lang.NullPointerException
at org.apache.maven.scm.provider.svn.svnexe.command.checkout.SvnCheckOutCommand.executeCheckOutCommand(SvnCheckOutCommand.java:86)
at org.apache.maven.scm.command.checkout.AbstractCheckOutCommand.executeCommand(AbstractCheckOutCommand.java:82)
at org.apache.maven.scm.command.AbstractCommand.execute(AbstractCommand.java:59)
... 8 more

sorry, I had created a script for the java -jar call, I guess. Is now some time ago.
I don't know why workingDirectory is null, I do nothing more fancy than what I just wrote.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Issue confirmed, I've been able to reproduce it

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Fixed in [rev. 1242108](http://svn.apache.org/viewvc?rev=1242108&view=rev)

The cause of this error is already in the beginning of the call, but only at the end it is causing trouble.
The reason: while reproducing this issue the workDirectory is a single filename. When the commandline is built it first calls `workingDirectory.getParent()` and then it uses its `getAbsolutePath()`. In this order the parent can't be calculated, so when calling the `getAbsolutePath()` you'll get your NPE. If the workingDirectory was `rx/ry` you would have had no problem.
