### ISSUE TITLE
[SCM-684] Mercurial - Unparseable date

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#890]
**[franek](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=franek)** opened **[SCM-684](https://issues.apache.org/jira/browse/SCM-684?redirect=false)** and commented

Scm Activity Plugin returns a warning for many lines of my code :

```
java.text.ParseException: Unparseable date: "<user@mail.com> c55d9b230751 Wed Jun 06 14:15:52 2012 +0200"
	at java.text.DateFormat.parse(DateFormat.java:337) ~[na:1.6.0_31]
	at org.apache.maven.scm.util.AbstractConsumer.parseDate(AbstractConsumer.java:112) ~[maven-scm-api-1.7.jar:1.7]
	at org.apache.maven.scm.provider.hg.command.blame.HgBlameConsumer.doConsume(HgBlameConsumer.java:71) [maven-scm-provider-hg-1.7.jar:1.7]
	at org.apache.maven.scm.provider.hg.command.HgConsumer.consumeLine(HgConsumer.java:131) [maven-scm-provider-hg-1.7.jar:1.7]
	at org.codehaus.plexus.util.cli.StreamPumper.consumeLine(StreamPumper.java:197) [plexus-utils-2.0.5.jar:na]
```

It is due to this command :

```
hg blame --user --date --changeset File.txt
```

It returns :

```
firstname lastname <user@mail.com> c55d9b230751 Tue Jun 19 14:20:07 2012 +0200:
```

Whereas the plugins expects (no space between firstname and lastname) :

```
firstnamelastname <user@mail.com> c55d9b230751 Tue Jun 19 14:20:07 2012 +0200:
```

---

**Affects:** 1.5

**Attachments:**
- [fix-hg-blame-parsing.patch](https://issues.apache.org/jira/secure/attachment/12718722/fix-hg-blame-parsing.patch) (_4.65 kB_)

3 votes, 5 watchers

**Comment by jira-importer** [comment]
**[franek](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=franek)** commented

The problem is resolved for Scm Activity Plugin (I have updated Jenkins and Sonar to the last version).

But I have got the same problem with ScmStatsPlugin.

```
 
EXECUTING: /bin/sh -c cd /var/lib/jenkins/jobs/<my project>/workspace/sources && hg log --verbose --no-merges --date '1970-01-02 to 2013-04-17'
09:26:27.996 WARN  .p.s.SonarScmManager - skip ParseException: Unparseable date: "Tue Apr 16 17:00:30 2013 +0200" during parsing date Tue Apr 16 17:00:30 2013 +0200 with pattern yyyy-MM-dd HH:mm:ss Z with Locale en
java.text.ParseException: Unparseable date: "Tue Apr 16 17:00:30 2013 +0200"
```

Perhaps, a solution could to run hg log with a template (http://hgbook.red-bean.com/read/customizing-the-output-of-mercurial.html#sec:template:filter) :

```
 
$ hg log -r1 --template 'date: {date|isodate}\n'
date: 2012-02-10 16:12 +0100
```

**Comment by jira-importer** [comment]
**[Vsevolod Minkov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vsevolod.minkov)** commented

Any news on this issue? It's really makes our CI server cry

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

This issue has been auto closed because it has been inactive for a long period of time. If you think this issue still applies, retest your problem with the most recent version of Maven and the affected component, reopen and post your results.
