### ISSUE TITLE
[SCM-687] Fix TFS Support

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#895]
**[Jonatan Urfalino](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jurfalino)** opened **[SCM-687](https://issues.apache.org/jira/browse/SCM-687?redirect=false)** and commented

When running SCM Activity Plugin for TFS you get hundreeds of "java.text.ParseException: Unparseable date" exceptions, because the 'tfpt annotate /nopromts' command does not return neither the date nor the author of each line, only the changeset number.
(Thus the second string that the plugin tries to find is not a date, but the file code itself)
Also see [SONARPLUGINS-373](http://jira.codehaus.org/browse/SONARPLUGINS-373?focusedCommentId=307289#comment-307289)

Error:

```
09:36:29.218 ERROR .s.ScmActivitySensor - Failure during SCM blame retrieval
java.lang.NullPointerException: null
	at java.util.Calendar.setTime(Calendar.java:1106) ~[na:1.7.0_03]
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:955) ~[na:1.7.0_03]
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:948) ~[na:1.7.0_03]
	at org.sonar.api.utils.DateUtils$ThreadSafeDateFormat.format(DateUtils.java:149) ~[sonar-plugin-api-3.1.1.jar:na]
	at java.text.DateFormat.format(DateFormat.java:336) ~[na:1.7.0_03]
	at org.sonar.api.utils.DateUtils.formatDateTime(DateUtils.java:55) ~[sonar-plugin-api-3.1.1.jar:na]
	at org.sonar.plugins.scmactivity.Blame.save(Blame.java:61) ~[na:na]
	at org.sonar.plugins.scmactivity.BlameVersionSelector.fileChanged(BlameVersionSelector.java:73) ~[na:na]
	at org.sonar.plugins.scmactivity.BlameVersionSelector.detect(BlameVersionSelector.java:57) ~[na:na]
	at org.sonar.plugins.scmactivity.ScmActivitySensor$1.call(ScmActivitySensor.java:110) ~[na:na]
	at org.sonar.plugins.scmactivity.ScmActivitySensor$1.call(ScmActivitySensor.java:108) ~[na:na]
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334) ~[na:1.7.0_03]
	at java.util.concurrent.FutureTask.run(FutureTask.java:166) ~[na:1.7.0_03]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) ~[na:1.7.0_03]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) ~[na:1.7.0_03]
	at java.lang.Thread.run(Thread.java:722) ~[na:1.7.0_03]
09:36:31.464 WARN  .p.s.SonarScmManager - skip ParseException: Unparseable date: "System.Configuration;" during parsing date System.Configuration; with pattern MM/dd/yyyy with Locale en
java.text.ParseException: Unparseable date: "System.Configuration;"
	at java.text.DateFormat.parse(DateFormat.java:357) ~[na:1.7.0_03]
	at org.apache.maven.scm.util.AbstractConsumer.parseDate(AbstractConsumer.java:112) [maven-scm-api-1.7.jar:1.7]
	at org.apache.maven.scm.util.AbstractConsumer.parseDate(AbstractConsumer.java:68) [maven-scm-api-1.7.jar:1.7]
	at org.apache.maven.scm.provider.tfs.command.blame.TfsBlameConsumer.consumeLine(TfsBlameConsumer.java:66) [maven-scm-provider-tfs-1.7.jar:1.7]
	at org.codehaus.plexus.util.cli.StreamPumper.consumeLine(StreamPumper.java:197) [plexus-utils-2.0.5.jar:na]
	at org.codehaus.plexus.util.cli.StreamPumper.run(StreamPumper.java:137) [plexus-utils-2.0.5.jar:na]
09:36:31.464 WARN  .p.s.SonarScmManager - skip ParseException: Unparseable date: "System.Web;" during parsing date System.Web; with pattern MM/dd/yyyy with Locale en
java.text.ParseException: Unparseable date: "System.Web;"
	at java.text.DateFormat.parse(DateFormat.java:357) ~[na:1.7.0_03]
	at org.apache.maven.scm.util.AbstractConsumer.parseDate(AbstractConsumer.java:112) [maven-scm-api-1.7.jar:1.7]
	at org.apache.maven.scm.util.AbstractConsumer.parseDate(AbstractConsumer.java:68) [maven-scm-api-1.7.jar:1.7]
	at org.apache.maven.scm.provider.tfs.command.blame.TfsBlameConsumer.consumeLine(TfsBlameConsumer.java:66) [maven-scm-provider-tfs-1.7.jar:1.7]
	at org.codehaus.plexus.util.cli.StreamPumper.consumeLine(StreamPumper.java:197) [plexus-utils-2.0.5.jar:na]
	at org.codehaus.plexus.util.cli.StreamPumper.run(StreamPumper.java:137) [plexus-utils-2.0.5.jar:na]
```

---

**Affects:** 1.7

0 votes, 5 watchers

**Comment by jira-importer** [comment]
**[Dinesh Bolkensteyn](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dinesh.bolkensteyn)** commented

FYI, I have developed a new tool to annotate files from TFS, which can act as a drop-in replacement for `tfpt.exe`. Moreover, it is faster, and open-source:

https://github.com/SonarCommunity/sonar-tfs

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

This issue has been auto closed because it has been inactive for a long period of time. If you think this issue still applies, retest your problem with the most recent version of Maven and the affected component, reopen and post your results.
