### ISSUE TITLE
[SCM-744] api's AbstractConsumer ignores Locale when using a custom dateFormatter

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#953]
**[Matías Albanesi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=malbanesi)** opened **[SCM-744](https://issues.apache.org/jira/browse/SCM-744?redirect=false)** and commented

Class org.apache.maven.scm.util.AbstractConsumer contains a method:

protected Date parseDate( String date, String userPattern, String defaultPattern, Locale locale )

Which ignores the specified locale if there is a userPattern specified. Current implementation is:
if ( StringUtils.isNotEmpty( userPattern ) )
{
format = new SimpleDateFormat( userPattern );
patternUsed = userPattern;
}

When the date parsing fails it misleadingly displays a message indicating that it did make use of the Locale but clearly it did not:

[ERROR] skip ParseException: Unparseable date: "Mon Oct 21 18:14:36 2013 -0300" during parsing date Mon Oct 21 18:14:36 2013 -0300 with pattern EEE MMM dd HH:mm:ss yyyy Z with Locale en
java.text.ParseException: Unparseable date: "Mon Oct 21 18:14:36 2013 -0300"
at java.text.DateFormat.parse(DateFormat.java:337)
at org.apache.maven.scm.util.AbstractConsumer.parseDate(AbstractConsumer.java:112)
at org.apache.maven.scm.provider.hg.command.changelog.HgChangeLogConsumer.doConsume(HgChangeLogConsumer.java:196)
at org.apache.maven.scm.provider.hg.command.changelog.HgChangeLogConsumer.consumeLine(HgChangeLogConsumer.java:97)
at org.codehaus.plexus.util.cli.StreamPumper.consumeLine(StreamPumper.java:195)

The issue happens because my environment has user.language=es, user.country=AR. Even passing these parameters in the command line does not help:

mvn clean changelog:changelog -Duser.language=en -Duser.country=US

fails the same way.

How this was tested:
- Mercurial repository
- using maven-changelog-plugin (specifying system parameters here does not help either)
  \<plugin>
  \<groupId>org.apache.maven.plugins\</groupId>
  \<artifactId>maven-changelog-plugin\</artifactId>
  \<version>2.2\</version>
  \<configuration>
  \<dateFormat>EEE MMM dd HH:mm:ss yyyy Z\</dateFormat>
  \<systemProperties>
  \<property>\<name>user.language\</name>\<value>en\</value>\</property>
  \<property>\<name>user.country\</name>\<value>US\</value>\</property>
  \</systemProperties>
  \</configuration>
  \</plugin>

---

**Affects:** 1.8.1

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

This issue has been auto closed because it has been inactive for a long period of time. If you think this issue still applies, retest your problem with the most recent version of Maven and the affected component, reopen and post your results.
