### ISSUE TITLE
[SCM-768] TfsBranchCommandTest is failing 

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#977]
**[Dan Tran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dantran)** opened **[SCM-768](https://issues.apache.org/jira/browse/SCM-768?redirect=false)** and commented

it is currently failing under 1.9.2-SNAPSHOT.

Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.028 sec <<< FAILURE! - in org.apache.maven.scm.provider.tfs.command.TfsBranchCommandTest
testCommandline(org.apache.maven.scm.provider.tfs.command.TfsBranchCommandTest)  Time elapsed: 0.016 sec  <<< FAILURE!
junit.framework.ComparisonFailure: null expected:<...login:user,password [C:\Users\trand8\dev\maven\maven-scm\maven-scm-providers\maven-scm-provider-tfs\target\scm-test\working-copy] -checkin branch">
but was:<...login:user,password [serverpath] -checkin branch">
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at org.apache.maven.scm.ScmTestCase.assertCommandLine(ScmTestCase.java:364)
at org.apache.maven.scm.provider.tfs.command.TfsBranchCommandTest.testCommandline(TfsBranchCommandTest.java:36)

---

**Issue Links:**
- [SCM-759](https://issues.apache.org/jira/browse/SCM-759) cannot create Branch with TFS-provider: "TF10125: The path must start with $/"

1 votes, 2 watchers

**Comment by jira-importer** [comment]
**[Dan Tran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dantran)** commented

fixed at

http://git-wip-us.apache.org/repos/asf/maven-scm/diff/b273f796
