### ISSUE TITLE
[SCM-242] NPE on ScmRepositoryException

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#996]
**[Julien HENRY](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=henryju)** opened **[SCM-242](https://issues.apache.org/jira/browse/SCM-242?redirect=false)** and commented

I get a NPE when using Scm plugin with the provider I wrote (Synergy) and the URL is incorrect.

I think it's because I use the ScmRepositoryException( String msg ) constructor instead of ScmRepositoryException( String msg, List validationMessages ), and the result is
e.getValidationMessages().isEmpty()
raise a NPE.

Here is stack trace :

java.lang.NullPointerException
at org.apache.maven.scm.plugin.AbstractScmMojo.getScmRepository(AbstractScmMojo.java:258)
at org.apache.maven.scm.plugin.CheckoutMojo.checkout(CheckoutMojo.java:94)
at org.apache.maven.scm.plugin.BootstrapMojo.execute(BootstrapMojo.java:58)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:412)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:534)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:488)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:458)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:306)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:219)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:140)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
...

---

**Attachments:**
- [NPE.patch](https://issues.apache.org/jira/secure/attachment/12718475/NPE.patch) (_542 bytes_)

**Comment by jira-importer** [comment]
**[Kenney Westerhof](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kenney)** commented

Fixed in svn revision 454658.

**Comment by jira-importer** [comment]
**[Julien HENRY](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=henryju)** commented

Here is a patch that fix the problem for me.

**Comment by jira-importer** [comment]
**[Julien HENRY](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=henryju)** commented

OK, your fix is better. ;)

**Comment by jira-importer** [comment]
**[Kenney Westerhof](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kenney)** commented

:) Thanks anyway!
